### ISSUE TITLE
Keep getting "Cannot GET" error with iisnode and Express

### ISSUE THREAD

**Issue by mfcollins3** [tjanczuk/iisnode#160]
I created a basic Express web application and set up my web.config file like the documentation shows:

```
<configuration>
    <system.webServer>
        <handlers>
            <add name=iisnode" path="myapp.js" verb="*" modules="iisnode"/>
        </handlers>
    </system.webServer>
</configuration>
```

I'm developing on Windows 7 and have my node application hosted in the root directory of an IIS web site.

When I enter the URL http://localhost:8888/myapp.js, I get the following:

```
Cannot GET /myapp.js
```

myapp.js is pretty basic:

```
var express = require('express');
var routes = require('routes');

var app = module.exports = express.createServer();
app.configure(function() {
    app.set('views', __dirname + '/views');
    app.set('view engine', 'jade');
    app.use(express.bodyParser());
    app.use(express.methodOverride());
    app.use(app.router);
});

app.configure('development', function() {
    app.use(express.errorHandler({
        dumpExceptions: true,
        showStack: true
    });
});

app.configure('production', function() {
    app.use(express.errorHandler());
});

app.get('/', routes.index);

port = process.env.PORT || 3000;
app.listen(port, function() {
    console.log("Server listening on port " + port + " in " + app.settings.env + " mode.");
});
```

If I run http://localhost:8000/myapp.js/debug, node inspector opens, but I don't see myapp.js in the list of loaded scripts. I see all of the express scripts and my routes/index.js script though.

Am I missing something or any hints on what to look for to fix it?

Thanks in advance.

**Comment by JeevFresno** [comment]
In my Case do i have to write the rewrite rules for all the paths or only for main files. Having hard time putting node js application on IIS server. thank you 

var mysql= require('mysql');
var favicon = require('serve-favicon');
var api = require('./routes/api');
var express = require('express');
var session = require('express-session');
var cookieParser = require('cookie-parser');
var bodyParser = require('body-parser');
var app = express();

//app.use is to define the pages and folder and basic usage
app.use(bodyParser.urlencoded({ extended: false }));
app.use('/public', express.static(__dirname + '/www/public'))
app.use('/view', express.static(__dirname + '/www/views/viewer'));
app.use('/', express.static(__dirname + '/www/views/models'));
app.use(favicon(__dirname + '/www/public/images/favicon1.ico'));
app.use('/api', api);

app.use(bodyParser.json());

app.set('port', process.env.PORT || 3000); //setting server port to 3000

var query="select label,urn from lmvmodeloption";   //to retrive the urn and label from lmvmodeloption

//Mysql Connection
var connection = mysql.createConnection({
    host : 'localhost',
    user :  'root',
    password :'',
    database: 'xx_xx',
    port: '3307',
});

//Get Function to check
app.get('/data', function(req, res){
    res.send('hello world'); //replace with your data here
});

/
app.get('/lmvmodels',function(req,res){
    connection.query(query,function(err,rows,fields){
        if(!err)
            res.send(rows);
        else 
            console.log(err.stack);
    });
});

//Logout function
app.post('/logout',function(req,res){
    console.log('Im logging out ');
    req.session = null;
    res.send('logout');
});

n
app.post('/endpoint',function(req,res){
    var user_name=req.body.user1;
    var password=req.body.password;
    //var d={ux:user_name,dx:password};
    console.log("User name = "+user_name+", password is "+password);
    var s='INSERT INTO lmvmodeloption(label,urn) '+
    'VALUES("'+password+'","'+user_name+'")';
    console.log(s);
    connection.query(s,function(err,res){
        if(err)
            throw err;
    });
    res.end("yes");
});
app.use(cookieParser())
app.use(session({secret: 'Keyboard car'}));
//this function takes care of the login, check if it returns the rows, if yes send success message, login success
app.post('/login',function(req,res){
    var p_wt=req.body.pass_w;
    var u_wt=req.body.user_w; var sess;
    //console.log(p_wt);
    //console.log(u_wt);
    var q= 'select email, password from user_login where email ="' +u_wt+ '" and password = "' +p_wt+ ' "';
    connection.query(q,function(err,rows,fields){
        //console.log(rows[0].email);
        if(rows.length>0){
            sess=req.session;
            sess.email_u=rows[0].email;
            console.log("Session="+ sess.email_u);
            console.log(rows);
            //console.log("success sent");
            console.log(rows[0].email);
            res.send("success");
        }
        else{
             res.send("Bad Data");
            console.log("bad data")
            // console.log(rows);
        }
    });

});

//Server is Starting on port 3000
var server = app.listen(app.get('port'), function() {

    connection.connect(function(err){
        if(err) {
            console.log('error connecting to the database' + err.stack);
            return;
        }
    });

   /* connection.query('SELECT email as first from user_login where email="jeevjyot.chhabda@whiting-turne"', function(err, rows, fields) {
        if (!err)
            console.log(rows);
        else
            console.log('Error while performing Query., Empty it is, no rows'+ err.stack);
    });*/
    console.log('Server listening on port ' +
        server.address().port);
});

//this function checks if no session is set, redirect the user to the index page
function checkAuth(req,res,nect){
    if(!sess.email_u){
        res.redirect("/");
    }
}

**Comment by dehildum** [comment]
I am running into the same error. In my case, the error is intermittent, and seems to occur only when the request needs a significant amount of processing. I suspect that IIS is timing out, as the node function completes successfully AFTER IIS has returned a 500 error.

**Comment by jayakumar4u** [comment]
Hi @tjanczuk,

I follow your above instruction, but still, I cannot retrieve my logged username, please help to resolve.

**My code below:
Config.xlm:** 

![image](https://user-images.githubusercontent.com/6740303/64399691-f88cdc00-d09b-11e9-9b90-f64a4374dd6e.png)

**app.js:**

 
![image](https://user-images.githubusercontent.com/6740303/64399733-283be400-d09c-11e9-9660-1a840d2d88cd.png)

Result:

![image](https://user-images.githubusercontent.com/6740303/64399751-3a1d8700-d09c-11e9-8405-c281a5bd4d8e.png)

IIS:
![image](https://user-images.githubusercontent.com/6740303/64399771-502b4780-d09c-11e9-98ed-9e73ff220c97.png)


I got empty username and authenticationType, any thing i want to do in the code or iis config?
please help to resolve

Thanks.

**Comment by jayakumar4u** [comment]
My Config.mxl:

<configuration>
    <system.webServer> 
       <iisnode 
            promoteServerVars="AUTH_USER,AUTH_TYPE"
            nodeProcessCommandLine="D:\PO\SSO\SSONODEIIS\node.exe" 
       />
        <handlers>
            <add name="iisnode" path="app.js" verb="*" modules="iisnode" />
        </handlers> 

        <rewrite>
            <rules>
                <rule name="sendToNode">
                    <match url="/*" />
                    <action type="Rewrite" url="app.js" />
                </rule>
            </rules>
        </rewrite> 

    </system.webServer>
</configuration>
