### ISSUE TITLE
support for x64 of node.js

### ISSUE THREAD

**Issue by tjanczuk** [tjanczuk/iisnode#178]
The iisnode MSI must be updated to check for x64 instead of x86 in this case
The default nodeProcessCommandLine may also require updates

**Comment by AxelBangert** [comment]
@kalehv
I have it in my path but I got the reference-error like all the others here. So I did it the same way as Kalev and changed web.conf and it runs:
 <iisnode
      nodeProcessCommandLine="C:\Program Files (x86)\nodejs\node.exe" 
      interceptor="&quot;%programfiles%\iisnode\interceptor.js&quot;" />
Best
Axel Arnold Bangert - Herzogenrath 05.2018
