### ISSUE TITLE
HTTP error 500.19 internal server error

### ISSUE THREAD

**Issue by yatendra** [tjanczuk/iisnode#214]
Hi, I am trying to deploy app written using express.js to new root website in iis using iisnode and am getting the following error - 
HTTP Error 500.19 - Internal Server Error
The requested page cannot be accessed because the related configuration data for the page is invalid.
Detailed Error Information
Module  IIS Web Core
Notification    Unknown
Handler Not yet determined
Error Code  0x8007000d
Config Error  
Config File \?\C:\websites\newsfeed\web.config
Requested URL   http://localhost:80/
Physical Path  
Logon Method    Not yet determined
Logon User  Not yet determined
Config Source
   -1: 
    0: 
Links and More Information
This error occurs when there is a problem reading the config

My web.config file is as follows - 

`<configuration>
    <system.webServer>
        <handlers>
            <add name="iisnode" path="app.js" verb="*" modules="iisnode" />
            </handlers>
            <iisnode loggingEnabled="false" />
            <rewrite>
                <rules>
                    <rule name="express">
                            <match url="*" />
                            <action type="Rewrite" url="app.js" />
                    </rule>
                </rules>
            </rewrite>
    </system.webServer>
</configuration>`

Has anyone else faced this issue before. Thanks in advance.

**Comment by nasimrizwee** [comment]
Thanks tjanczuk,

url-rewrite was missing, and you saved my lots of time.

Nasim
