### ISSUE TITLE
Node path

### ISSUE THREAD

**Issue by pcibraro** [tjanczuk/iisnode#22]
You state in the documentation that node should be located at %systemdrive%\node directory. Is there any chance to use the environment variable NODE_PATH, which is the same variable as Node uses for resolving the external module dependencies in windows ?.

Thanks
Pablo.

**Comment by nickhudkins** [comment]
@tjanczuk I don't believe this is the case as I have set NODE_PATH and it seems that iisnode ignores it? Is there something I am missing here?

**Comment by judowalker** [comment]
@nickhudkins @tjanczuk this is happening for me as well. 

My global modules are located here by default (`NODE_PATH` is also set to this): 
```
%USERPROFILE%\AppData\Roaming\npm\node_modules
```

My node.exe is located here by default: 
```
%programfiles%\nodejs\node.exe
```

In the web.config file I set this:
```
<iisnode nodeProcessCommandLine="&quot;%programfiles%\nodejs\node.exe&quot;" />
```
I get an error that module cannot be found.
