### ISSUE TITLE
Allow all iisnode settings to be configured via environment variables

### ISSUE THREAD

**Issue by glennblock** [tjanczuk/iisnode#220]
All vars should have an iisnode- prefix, for example IISNODE-ENABLEDEBUGGING. This will make it easy to configure iisnode from the Azure portal.

Here is the order of precedence for how config values will be read
1. Env vars
2. iisnode.yml
3. web.config
   @gissues:{"order":72.4609375,"status":"notstarted"}

**Comment by bjrmatos** [comment]
sorry but i can't find any example on google of how to setup Environment variables for the IIS worker process :( could you please guide me a little?

**Comment by Siafu** [comment]
@bjrmatos  take a look at this sample web.config https://gist.github.com/pbaio/f63918181d8d7f8ee1d2 . It's setting up the virtualDirPath environment variable.

**Comment by Siafu** [comment]
Also you can specify variables  by adding stuff like LOGON_USER to the promoteServerVars option within iisnode settings section.

**Comment by bjrmatos** [comment]
thnks @Siafu!! :)
