### ISSUE TITLE
Serving meteorjs app through IISNODE

### ISSUE THREAD

**Issue by anu-rock** [tjanczuk/iisnode#235]
At my work, we are tied to the Microsoft platform for development and hosting. I needed to deploy our meteorjs app on a Windows 2008 R2 server and almost deployed it using "Vagrant VM" solution when I found out about this good IIS module called iisnode. So I installed nodejs, mongodb and iisnode on our Windows Server, bundled my meteorjs app (in Linux), replaced the Linux binaries of node-fiber inside that bundle with corresponding Windows ones, setup System-wide environment variables MONGO_URL and ROOT_URL, and finally deployed my meteorjs app to be served using iisnode. Now with everything setup correctly, it should have worked out fine, but it didn't. Instead, I got an "Internal Server Error" as reported by iisnode.

A little googling showed that [someone else had also faced the same error](https://github.com/meteor/meteor/issues/241), but their problem was unresolved. I suspected that the issue could be because iisnode sets the PORT environment variable to a named pipe, to facilitate port sharing between IIS and node, and I found [this](https://github.com/tjanczuk/iisnode/issues/46). I thought the pipe thingy made the code in server.js blow up in my meteorjs app where it says:

``` javascript
app.listen(process.env.PORT, function() {
  if (argv.keepalive)
    console.log("LISTENING"); // must match run.js
});
```

I even tried with the 1 argument overload of the listen function, but still got the same error.

``` javascript
app.listen(process.env.PORT);
```

On debugging using ETW, I got [a log very similar to this](https://www.tropo.com/hosting/FTPServlet/iisnode.etl.xml?&location=attachment&jsessionid=676C48D334CADDC580DAFECCB9A0C7C7.node1&cmd=get&dir=94%2F1782483%2F0%2F322f23ac499f7512b19f6b3ce146f7df&file=iisnode.etl.xml).

Does anyone know if there is a way around this problem? In other words -- is it possible to host a meteorjs app using iisnode?

Thanks.

**Comment by IRIS-FieldService** [comment]
@anuragbhd , Tried the link you provided, seems site is down right now, could you please make it up again.

**Comment by lmvijay24** [comment]
@anuragbhd  , Tried the link you provided, seems site is down right now, could you please make it up again.

**Comment by anuragbhd** [comment]
Try this:
http://www.anuragbhandari.com/blog/2012/11/hosting-meteor-js-app-in-iis/
