### ISSUE TITLE
Windows Azure Websites is overriding my 404 and 500 error pages in my node.js app

### ISSUE THREAD

**Issue by BeekeeperAlex** [tjanczuk/iisnode#261]
I am using Windows Azure Websites to host a node.js application. So far everything is great except for my custom errors. In my node app I have an error handler that renders a custom 404 and custom 500 error page just fine on my local machine. However, as soon as I publish to azure it overrides the response when I set the statusCode to anything except 200.

If I don't pass the 500 or 404 statusCode to the response then this does not happen, but I do want the status codes to make it to the browser. Locally I get my custom error page just fine:

![](http://i.imgur.com/aYNLk4W.png)

However, on azure websites it only returns a single line of text:

> The page cannot be displayed because an internal server error has occurred.

I tried creating my own web.config to override the default one with custom errors disabled but that didn't seem to have any effect. Here is my web.config:

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
    <system.web>
        <customErrors mode="off" />
    </system.web>
    <system.webServer>
        <handlers>
            <add name="iisnode" path="app.js" verb="*" modules="iisnode"/>
        </handlers>
        <rewrite>
            <rules>
                <rule name="StaticContent">
                    <action type="Rewrite" url="public{REQUEST_URI}"/>
                </rule>
                <rule name="DynamicContent">
                    <conditions>
                        <add input="{REQUEST_FILENAME}" matchType="IsFile" negate="True"/>
                    </conditions>
                    <action type="Rewrite" url="app.js"/>
                </rule>
            </rules>
        </rewrite>
        <iisnode
            debuggingEnabled="true"
            devErrorsEnabled="true"
            debuggerPathSegment="debug"
            nodeProcessCommandLine="&quot;%programfiles(x86)%\nodejs\node.exe&quot;"
            logDirectory="..\..\LogFiles\nodejs"
            watchedFiles="*.js;iisnode.yml;node_modules\*;views\*.jade;views\*.ejb;routes\*.js" />
    </system.webServer>
</configuration>
```

I'm not sure if `iisnode` is responsible for overriding my error pages or if iis itself is responsible. Any suggestions?

**Comment by snake-plissken** [comment]
Sorry to resurrect an old ticket @chevtek and https://github.com/Azure/iisnode crew but this ticket just helped me fix the same problem in Azure.  Adding  a few keywords/phrases so maybe it can pop up on search engines without a good amount of digging:
Azure web app overwriting status codes
Azure IIS config MVC status codes
Azure web app status codes not working
Azure web app custom status codes 400 500
