### ISSUE TITLE
The Module DLL C:\Program Files (x86)\iisnode\iisnode.dll failed to load

### ISSUE THREAD

**Issue by 1bit** [tjanczuk/iisnode#267]
My System:
- Windows Webserver 2008 R2 x64
- IIS7
- Node v0.10.0 installed in "C:\Program Files\nodejs"
- iisnode-full-iis7-v0.2.3-x64.msi installed in "C:\Program Files (x86)\iisnode"
  IISNode is installed via "msiexec /i iisnode-full-iis7-v0.2.3-x64.msi WOW=1"
- Plesk 11

The Testsite works fine when Application Pool is set "Enable 32-bit applications" = True

Unfortunately all other sites with Application Pools setting "Enable 32-bit applications" = False are crashing all the time, throwing "The Module DLL iisnode.dll failed to load" / Error 503 in Browser.

Trying to restart the Webserver fails with reporting "The Module DLL iisnode.dll failed to load" for each Site with Application Pools setting "Enable 32-bit applications" = False.

I have to work with the two different Application Pools, 32 Bit enabled and disabled.
Is there a way for it?

Thank you very much in advance.
And thank you generally very much for your great work to bring node.js to IIS!

**Comment by OZZlE** [comment]
I was getting this until I just went to IIS Application > root > modules and added iisnode there and everything started working.

there seems to already be an "IISNode" that I could pick there as well so now I'm wondering if it's all built in and if I just wasted a lot of time installing it from here and trying to set it up properly..
