### ISSUE TITLE
Getting 503

### ISSUE THREAD

**Issue by peterkroon** [tjanczuk/iisnode#27]
Hello,
Not sure if I should post this here...
I just installed iisnode and keep getting an 503 error on al my pages.
Any suggestions on this matter?
Thanks,
Peter

Add:
For some reason DefaultAppPool stops when trying to access a page or folder on the server.
The 503 comes from HTTP.sys because the pool is stopped. Mostlikely due to too much errors.
When I set the value of "Quick security against errors" to false the request keeps 'polling'.
Note: I have a dutch iis. So I tried to translate some iis feateures to english.

**Comment by cjxin2017** [comment]
http error 503
win2008 r2 x64 IIS7.5 
Application pool Automatic stop

Local environment: win10 X64 bit, normal use, local development environment installed Visual Studio 2013

It should be a lack of corresponding SDK in the server environment. It is impossible to resolve the official documents of Microsoft, install windows sdk7.1 and Web Platform.

Detailed error content：
- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="Microsoft-Windows-IIS-W3SVC-WP" Guid="{670080D9-742A-4187-8D16-41143D1290BD}" EventSourceName="W3SVC-WP" /> 
  <EventID Qualifiers="49152">2280</EventID> 
  <Version>0</Version> 
  <Level>2</Level> 
  <Task>0</Task> 
  <Opcode>0</Opcode> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2018-05-02T03:44:29.000000000Z" /> 
  <EventRecordID>17654</EventRecordID> 
  <Correlation /> 
  <Execution ProcessID="0" ThreadID="0" /> 
  <Channel>Application</Channel> 
  <Computer>10_163_28_249</Computer> 
  <Security /> 
  </System>
- <EventData>
  <Data Name="ModuleDll">C:\BtSoft\WebSoft\web\waf_iis_test.dll</Data> 
  <Binary>7E000000</Binary> 
  </EventData>
  </Event>
