### ISSUE TITLE
iisnode and custom http errors

### ISSUE THREAD

**Issue by rnikitin** [tjanczuk/iisnode#295]
Hi, we are building a REST API and we want to return any error and fault HTTP state with JSON body, contains error description. And we are deploying to Windows Azure WebSites.

Example code:

``` js
app.get("/error1", function(req, res){
    res.json(503, {desc: "something went wrong.", errcode: 1101});
});
```

We discovered, that iisnode handles this errors and rewrites the body. 
Is there a way to prevent it from doing this?

**Comment by pcomerford** [comment]
So, in case anyone out there is applying the `<httpErrors existingResponse="passthrough" />` fix, be sure to try `<httpErrors existingResponse="PassThrough" />`  instead.
