### ISSUE TITLE
Process arguments cannot be parsed (i.e. --harmony)

### ISSUE THREAD

**Issue by bastiankistner** [tjanczuk/iisnode#315]
I tried to get an instance of node.js 0.11.9 running on Azure which works fine so far via nodeProcessCommandLine and a custom binary  - but sadly I couldn't figure out any possible way to pass additional process arguments that are available for process.execArgv .

I'd love to try out Koa on Azure but as long as it's not possible to enable --harmony-generators, it's not going to work.

I'd also be glad if there is another workaround that I haven't found yet.

If there is no other option, why can't we just pass additional arguements to the nodeProcessCommandLine key? If I try it like "nodeProcessCommandLine --harmony-generators" my app just crashes.

Thanks and best,
Bastian

**Comment by viorelfilip** [comment]
Replace in Web.config the line <iisnode watchedFiles="web.config;*.js" /> with
    <iisnode watchedFiles="web.config;*.js" nodeProcessCommandLine="node.exe &#45;&#45;harmony"/>

**Comment by joebartels** [comment]
this burned me for a while. I couldn't just remove the double quotes cause the path had spaces:
`"D:\Program Files (x86)\nodejs\5.1.1\node.exe"`

This is what ended up working:
```bash
nodeProcessCommandLine: "D:\Program Files (x86)\nodejs\5.1.1\node.exe" --harmony_destructuring
```

**Comment by tony-gutierrez** [comment]
Has anyone successfully added a flag in web.config as opposed to iisnode.yml?

**Comment by pawelgur** [comment]
Had same issue with web.config, managed to set it up in following way:
`nodeProcessCommandLine="&quot;%programfiles%\nodejs\node.exe&quot; --preserve-symlinks"`

Before tried referencing custom `.bat` file that included just `node --preserve-symlinks` but iis-node failed to communicate with node started in this way.
