### ISSUE TITLE
IIS server variables updated by custom http module not promoted with latest values

### ISSUE THREAD

**Issue by timgit** [tjanczuk/iisnode#317]
I used the solution in issue https://github.com/tjanczuk/iisnode/issues/87 to successfully pass the server variables to node.  However, I modified a server variable in my own http module (that I can step through in the debugger before the handler is executed), and the promoted server variable is still picking the previous value.  I have confirmed that a standard ASP.NET page sees the changed server variable.  

It could be that I'm not setting the server variable properly (AUTH_USER), as the only method I could find involved replacing the current principal (Windows in my case) with GenericPrincipal in my module.

**Comment by nsharrok** [comment]
I too need to have AUTH_USER propagate through to x-iisnode-auth_user. 
Can you explain in a little more detail what you did?

**Comment by PeterMurdoch** [comment]
@nsharrok I had this problem after applying passive wsFederation redirection.  The solution I came up with was to override the postauthenticaterequest event, add the header with a null terminator, then trim the null terminator out if present once passed around.
