### ISSUE TITLE
iisnode internal server error...

### ISSUE THREAD

**Issue by xaki85** [tjanczuk/iisnode#319]
i have deployed a simple node.js application for streaming audio, its working pretty fine on my local machine by cmd.exe but on iis while it is giving a server internal error, below is my error details, one can see that streaming is being done as shown in the output generated by the node.exe process but still internal server error.

im using windows 7 (64 bit) and IIS 7 with latest nodejs and iisnode.
can somebody tell me how to resolve this, plz.....?

iisnode encountered an error when processing the request.

HRESULT: 0xb
HTTP status: 500
HTTP reason: Internal Server Error
You are receiving this HTTP 200 response because system.webServer/iisnode/@devErrorsEnabled configuration setting is 'true'.

In addition to the log of stdout and stderr of the node.exe process, consider using debugging and ETW traces to further diagnose the problem.

The last 64k of the output generated by the node.exe process to stdout and stderr is shown below:

Client connected; streaming
Radio Stream connected!
undefined
<Buffer 53 74 72 65 61 6d 54 69 74 6c 65 3d 27 27 3b>
Client connected; streaming
Client connected; streaming
Client connected; streaming
Client connected; streaming
Client connected; streaming

**Comment by vilic** [comment]
@rramachand21 Facing the same error, but not every request. Seems to happen randomly (about 1 / 20).

**Comment by kierenj** [comment]
Also seeing this randomly, with no errors logged
