### ISSUE TITLE
Unknown stdin file type

### ISSUE THREAD

**Issue by calebolin** [tjanczuk/iisnode#337]
I have iisnode working smoothing on win8/IIS8. I created a very simple hello world and it works great. However, when I try to use process.stdin I get the following error:

```
Application has thrown an uncaught exception and is terminated:
Error: Implement me. Unknown stdin file type!
    at process.startup.processStdio.process.openStdin [as stdin] (node.js:405:17)
    at Object.<anonymous> (C:\ApprendaPlatform\SiteData\developer\v1\root\shim\node_modules\actionhero\bin\zzz.js:7:20)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:362:17)
    at require (module.js:378:17)
    at Object.<anonymous> (C:\Program Files\iisnode\interceptor.js:210:1)
    at Module._compile (module.js:449:26)
```

Note that I do not get this with process.stdout.

My code:

```
// kaboom!
var breakthings = process.stdin;

// works
// var breakthings = process.stdout;
```

**Comment by BrianKrohn** [comment]
Bump.  Using ActionHero is not a resolution to this issue.

**Comment by megakoresh** [comment]
Having this with SailsJS app. Anyone still on this case?

**Comment by sebastiankr** [comment]
Having this with socketcluster.io. Isn't the solution for iisnode to provide a dummy process.stdin instead of having to change every dependency?

**Comment by allens01** [comment]
Is there any update on this issue? I am also having the issue with socketcluster.io.

**Comment by organom** [comment]
As a workaround I'm doing this on the iisnode js file:

```
var events = require('events');

delete process.stdin;
process.stdin = new events.EventEmitter();

```
hope it helps ;)

**Comment by PyDeq** [comment]
So, this is already two years old and still no response? I wonder how Microsoft can build their paid solution on something that has no support...

**Comment by BrianKrohn** [comment]
IIS and iisnode are not the issue.  The issue is with Node.js.  It requires the console as output, but iisnode is a headless process and has no console.  Don't a start trolling MS on this forum, when Node.js is the culprit.

**Comment by PyDeq** [comment]
Well, what I meant is Azure... Azure supports Node.js applications via IISNode... So, are you saying that this is not a bug in IISNode and that it should be reported against Node.js?

**Comment by BrianKrohn** [comment]
It's not really a bug.  Node.js uses the console for input.  It's been
awhile since I dealt with this, but I seem to remember that you need to out
code in your app to set the console input to null, or something like that.

**Comment by PyDeq** [comment]
Well, strictly speaking, if there is something that I need to do in order to be able to run my app using IISNode, it should be documented somewhere. If it isn't, it's *at least* a bug in the documentation...

**Comment by calebolin** [comment]
I agree with PyDeq. Node apps that work without error  in other contexts throw errors in iisnode. That sure seems like a bug to me.

**Comment by pbaio** [comment]
@BrianKrohn This is incorrect

> IIS and iisnode are not the issue. The issue is with Node.js. It requires the console as output, but iisnode is a headless process and has no console. Don't a start trolling MS on this forum, when Node.js is the culprit.

Node uses `process.stdin`, `process.stdout` and `process.stderr` for input, output and errors, `console.log()` just writes to the stream provided to `process.stdout`.

**Comment by BrianKrohn** [comment]
Sry, stdin is what I meant, not console.  In any case, iisnode does not
provide a process.stdin or process.stdout, because it's not a console with
those capabilities.  You get what I'm saying.

**Comment by calebolin** [comment]
Closing for age
