### ISSUE TITLE
Nested server.js

### ISSUE THREAD

**Issue by futurechan** [tjanczuk/iisnode#338]
I having trouble getting iisnode to run my node application. 
My directory structure is

```
iis-site
   -client
   -server
      -server.js
```

How can I get iisnode to point to a nested .js file? I tried this, but it servers the server.js instead of executing it.

```
<handlers>
    <add name="iisnode" path="server\server.js" verb="*" modules="iisnode" />
 </handlers>

and

<rule name="default">
       <match url="/*" />
        <conditions logicalGrouping="MatchAll" trackAllCaptures="false" />
        <action type="Rewrite" url="server/server.js" />
</rule>
```

**Comment by moorthi07** [comment]
This option still not working in webmatrix iisnode / iisexpress. When you try require(__dirname + '\\server\\server.js'); - it just listing the actual code in the browser!  Any idea what am I missing?

**Comment by rramachand21** [comment]
did you change you web.config ? please paste web.config

**Comment by moorthi07** [comment]
Trying to make it work on iis with webmatrix.

When I run from webmatrix , it just displays the actual code of server/server.js. (I tried the starter node project also , moving server.js to a new folder same as below )

How can I point the start application work from a subfolder.
package.json:

"main": "./server/server.js",

web.confing 

 <add name="iisnode" path="./server/server.js" verb="*" modules="iisnode" />

  <action type="Rewrite" url="./server/server.js" />

full web.config:
<configuration>
  <system.webServer>

    <handlers>
      
      <add name="iisnode" path="./server/server.js" verb="*" modules="iisnode" />
      

    </handlers>

    <rewrite>
      <rules>        
        
        <rule name="NodeInspector" patternSyntax="ECMAScript" stopProcessing="true">
          <match url="^server\/server.js\/debug[\/]?" />
        </rule>

        
        

        
        <rule name="DynamicContent">
          <conditions>
            <add input="{REQUEST_FILENAME}" matchType="IsFile" negate="True" />
          </conditions>
          <action type="Rewrite" url="./server/server.js" />
          
        </rule>
      </rules>
    </rewrite>

    

    <iisnode      
          node_env="%node_env%"
          nodeProcessCountPerApplication="1"
          maxConcurrentRequestsPerProcess="1024"
          maxNamedPipeConnectionRetry="3"
          namedPipeConnectionRetryDelay="2000"      
          maxNamedPipeConnectionPoolSize="512"
          maxNamedPipePooledConnectionAge="30000"
          asyncCompletionThreadCount="0"
          initialRequestBufferSize="4096"
          maxRequestBufferSize="65536"
          watchedFiles="*.js"
          uncFileChangesPollingInterval="5000"      
          gracefulShutdownTimeout="60000"
          loggingEnabled="false"
          debuggingEnabled="true"
          debuggerPortRange="5058-6058"
          debuggerPathSegment="debug"
          maxLogFileSizeInKB="128"
          devErrorsEnabled="true"
          flushResponse="false"      
          enableXFF="false"
          promoteServerVars=""
         /> 

  </system.webServer>
</configuration>

**Comment by moorthi07** [comment]
Any updates? Is this a limitation ? 
-----
IISNode  lists the source code of the file if your server.js is in different folder (like server/server.js). Even if you put a server.js in the root with require ('\\server\\server.js') - it doesn't work. Any idea?
