### ISSUE TITLE
Detect connection termination (response close event)

### ISSUE THREAD

**Issue by KooiInc** [tjanczuk/iisnode#358]
I wrote a small longpoll experiment, using nodejs/iisnode. It runs a loop with a given amount of iterations in timeout handlers, returning a tuple, used in the client (see link @ the bottom here).

This works fine, but there's one issue. Using iisnode, this little piece of code doesn't work:

```
res.on('close', function () {
                   res.socketIsClosed = true;
                   res.end();
                 }
);
```

Later on `res.socketIsClosed` is used to determine if the running loop can be finished. In iisnode however the loop _always_ runs to the end, connectiion or not.

If I run the code in a 'plain' node server, it _does_ pickup the `close` event, e.g. after a page reload before the longpoll is finished.

Is there a way to make iiisnode listen to the `close` event?

The iisnode service is called from [here](http://testbed.nicon.nl/slownode/), or you may use cURL: `curl testbed.nicon.nl/slownode/poll?repeat=5`

The nodejs source code can be found  [here](http://testbed.nicon.nl/slownode/poll?getcode)

sample log from iisnode:

```
longpoll started, req id => aece3
request aece3 still alive, continuing ...
request aece3 still alive, continuing ...
request aece3 still alive, continuing ...
request aece3 still alive, continuing ...
**page refresh around here
request aece3 still alive, continuing ...
request aece3 still alive, continuing ...
longpoll ended, it lasted 30.08seconds, the reqid was aece3
longpoll started, req id => c4b04
request c4b04 still alive, continuing ...
request c4b04 still alive, continuing ...
request c4b04 still alive, continuing ...
request c4b04 still alive, continuing ...
request c4b04 still alive, continuing ...
request c4b04 still alive, continuing ...
longpoll ended, it lasted 38.09seconds, the reqid was c4b04
```

sample log from plain node:

```
longpoll started, req id => 4918f
request 4918f still alive, continuing ...
request 4918f still alive, continuing ...
request 4918f still alive, continuing ...
request 4918f still alive, continuing ...
*page refresh here
longpoll started, req id => c3fb7
request c3fb7 still alive, continuing ...
request 4918f died, terminating the loop.
request c3fb7 still alive, continuing ...
request c3fb7 still alive, continuing ...
request c3fb7 still alive, continuing ...
request c3fb7 still alive, continuing ...
request c3fb7 still alive, continuing ...
longpoll ended, it lasted 37.02seconds, the reqid was c3fb
```

**Comment by KooiInc** [comment]
Not using iisnode anymore, wrote my own stub.

**Comment by rramachand21** [comment]
This was fixed in https://github.com/Azure/iisnode/commit/f9a66d83028480b94156e31b91b9bc3d92394367 - this change was also integrated into this branch,
