### ISSUE TITLE
Set the node_paths environment variable before server starts

### ISSUE THREAD

**Issue by mathew-kurian** [tjanczuk/iisnode#366]
How do we set the environmental variables that are set before the nodejs server is started?

Thank you!

**Comment by Delphinidae84** [comment]
@bluejamesbond So how is this done?

**Comment by pbaio** [comment]
You can use the `<appSettings>` Config Section to specify environment variables using IISNode.

```
<appSettings>
  <add key="SOME_VAR" value="VAR_VALUE" />
</appSettings>
```

Inside your app, you can then access `SOME_VAR` on your `process.env` object when your app first starts using `process.env.SOME_VAR`.
