### ISSUE TITLE
Websockets not working on Azure Webrole and IISNode

### ISSUE THREAD

**Issue by nikhilhasija** [tjanczuk/iisnode#367]
I am trying to get websockets to work on Azure Webrole and keep getting this error:
Error during WebSocket handshake: Unexpected response code: 400

node.js 0.10.21
iisnode 0.2.11
webSocket enabled = "false"

Don't know where the 400 is coming from. The app itself (node app) works fine when it is self-hosted.

**Comment by KngHawkon** [comment]
Hi, I have this problem with v0.2.21 and socket.io, any thoughts?
