### ISSUE TITLE
Node.js compression VS IIS compression

### ISSUE THREAD

**Issue by nickdima** [tjanczuk/iisnode#387]
How it's best to handle the gzip compression for dynamic content (server side generated pages)?
Should we let IIS handle it or disable it from IIS and do it in node?

**Comment by wy193777** [comment]
How to disable iisnode compression? I put following lines into <system.webServer> on my nodejs app root, but has no affect when deploy to Azure App Service Windows:
```xml
    <urlCompression doStaticCompression="false" doDynamicCompression="false" />
    <httpCompression>
        <dynamicTypes>
        <clear />
        <add enabled="false" mimeType="text/*"/>
        <add enabled="false" mimeType="message/*"/>
        <add enabled="false" mimeType="application/x-javascript"/>
        <add enabled="false" mimeType="application/javascript"/>
        <add enabled="false" mimeType="application/json"/>
        <add enabled="false" mimeType="*/*"/>
        <add enabled="false" mimeType="application/atom+xml"/>
        <add enabled="false" mimeType="application/atom+xml;charset=utf-8"/>
        </dynamicTypes>
        <staticTypes>
        <clear />
        <add enabled="false" mimeType="text/*"/>
        <add enabled="false" mimeType="message/*"/>
        <add enabled="false" mimeType="application/javascript"/>
        <add enabled="false" mimeType="application/atom+xml"/>
        <add enabled="false" mimeType="application/xaml+xml"/>
        <add enabled="false" mimeType="application/json"/>
        <add enabled="false" mimeType="*/*"/>
        </staticTypes>
    </httpCompression>
```

**Comment by debben** [comment]
I have the same issue. I'm trying to use an IIS outbound rewrite rule to replace matched text. I'm getting errors claiming the HTTP response from iisnode is returning a gzip encoded response and that outbound rules cannot be applied to such a response body. I've tested my node application with just node.exe and curl to try varying forms of "Accept-Encoding" and my node app isn't compressing the response. I'm wondering if this is being done by iisnode and how to turn it off.

**Comment by tverilytt** [comment]
Have anyone done some compression performance comparison between IIS and iisnode Node.js?
E.g IIS Dynamic Compression vs Node.js Express Compression package?

Cheers
-jo
