### ISSUE TITLE
IISNode inspector returns websocket failed

### ISSUE THREAD

**Issue by noynir** [tjanczuk/iisnode#388]
i installed iisnode on a windows8 and 8.1 also installed the samples and they are all running except the debugger (node inspector) in the browser console i get the following error:

WebSocket connection to 'ws://localhost/node/helloworld/hello.js/debug/ws?' failed: Error during WebSocket handshake: 'Connection' header value is not 'Upgrade': Upgrade Upgrade

websockets feature is installed. When running node inspector thorough CMD it works.

any ideas?

**Comment by ericterpstra** [comment]
I'm having the exact same issue.  The examples work fine, but node-inspector does not work.  The error is similar to @noynir : 

```
WebSocket connection to 'ws://scorecard.melodi2.methodisthealth.org/hello.js/debug/ws' failed: Error during WebSocket handshake: Unexpected response code: 200
```

I am running **Windows Server 2012** with **IIS 8.5**. Node.js is 0.12.7 and iisnode is 0.2.18 (x64)

I've added `<webSocket enabled="false" />` as recommended by [Microsoft](http://www.iis.net/learn/get-started/whats-new-in-iis-8/iis-80-websocket-protocol-support) and it had no effect (even after restarting the website).

**Comment by rramachand21** [comment]
could you please paste your web.config here?

**Comment by ericterpstra** [comment]
It's basically the one that comes with the iisnode examples, but with `<webSocket enabled="false" />

```xml
<configuration>
  <system.webServer>

    <!-- indicates that the hello.js file is a node.js application 
    to be handled by the iisnode module -->

    <handlers>
      <add name="iisnode" path="hello.js" verb="*" modules="iisnode" />
    </handlers>

    <!-- use URL rewriting to redirect the entire branch of the URL namespace
    to hello.js node.js application; for example, the following URLs will 
    all be handled by hello.js:
    
        http://localhost/node/urlrewrite/myapp
        http://localhost/node/urlrewrite/myapp/foo
        http://localhost/node/urlrewrite/myapp/foo/bar/baz?param=bat
        
    -->
    
    <rewrite>
      <rules>
        <rule name="myapp">
          <match url="myapp/*" />
          <action type="Rewrite" url="hello.js" />
        </rule>
      </rules>
    </rewrite>
	<webSocket enabled="false" />
  </system.webServer>
</configuration>
```

**Comment by noynir** [comment]
same web.config as @ericterpstra , still not working on windows 10 also...
![iisnode](https://cloud.githubusercontent.com/assets/8056070/9598068/7c063850-5090-11e5-8739-275b42274571.PNG)

**Comment by pbaio** [comment]
Try adding this in your handler instead of the one you are currently using. 

```
          <add name="iisnode-socket.io" path="hello.js" verb="*" modules="iisnode" />
```

**Comment by noynir** [comment]
thx @pbaio but still no luck :(

**Comment by pbaio** [comment]
Also try adding the following into your Web.config in your `<rewrite>` section

```
    <rule name="SocketIO" patternSyntax="ECMAScript">
      <match url="socket.io.+" />
      <action type="Rewrite" url="hello.js"/>
    </rule>
```

**Comment by ericterpstra** [comment]
What's particularly disturbing about this issue is that the web.config in question is provided by the IISNode project itself in the examples folder.  The real problem here is that IISNode appears to have been abandoned by its original author and forked by Microsoft who is largely ignoring the project.  Issues over the past 2 months have gone unanswered and there has been one bugfix/commit since May in the Azure fork.  

It would be nice if there were some sort of official statement from Microsoft on the status of this project, and whether or not we can expect it to be maintained.

Sorry if this sounds like a rant, but I spent several days trying to get IISNode working with my app only to give up and use IIS as a reverse proxy to a PM2 instance managing all Node.js processes.

**Comment by rramachand21** [comment]
Sorry that your question was not answered - As a workaround for now, you can set the <iisnode debuggerExtensionDll="iisnode-inspector.dll" /> to use the old node inspector because the old node inspector does not use websockets. 

Would you be able to share your application with me so I can debug whats going on and why the new node inspector is not working with your configuration?

**Comment by pbaio** [comment]
Why not try creating the following in the rewrite section instead

```
        <rewrite>
            <rules>
                <!-- Don't interfere with requests for node-inspector debugging -->
                <rule name="NodeInspector" patternSyntax="ECMAScript" stopProcessing="true">
                    <match url="^hello.js\/debug[\/]?" />
                </rule>
 
                <!-- First we consider whether the incoming URL matches a physical file in the /public folder -->
                <rule name="StaticContent" patternSyntax="Wildcard">
                    <action type="Rewrite" url="public/{R:0}" logRewrittenUrl="true" />
                    <conditions>
                            <add input="{REQUEST_FILENAME}" matchType="IsFile" negate="true" />
                    </conditions>
                    <match url="*.*" />
                  </rule>
 
                <!-- All other URLs are mapped to the Node.js application entry point -->
                <rule name="DynamicContent">
                    <conditions>
                        <add input="{REQUEST_FILENAME}" matchType="IsFile" negate="True" />
                    </conditions>
                    <action type="Rewrite" url="hello.js" />
                </rule>
                <rule name="SocketIO" patternSyntax="ECMAScript">
                  <match url="socket.io.+" />
                  <action type="Rewrite" url="hello.js"/>
                </rule>
            </rules>
        </rewrite>
```

**Comment by pbaio** [comment]
@ericterpstra the configuration of IIS Node and the documentation is lacking to say the least not because it is incomplete necessarily but, because of how fragmented it is, aside from the blog that Tomasz had been using to tutorials. 

This Web.config I have used in the past to figure out exactly how to configure IIS Node and it does have some options for debugging with node inspector starting on [line 74](https://github.com/tjanczuk/iisnode/blob/master/src/samples/configuration/web.config#L74)

**Comment by Siafu** [comment]
Is anyone working on this issue? I have tried everything listed in the comments to no avail.

**Comment by rramachand21** [comment]
As a workaround for now, you can set the to use the old node inspector because the old node inspector does not use websockets. - Please set debuggerExtensionDll="iisnode-inspector.dll" in the iisnode config

**Comment by ericterpstra** [comment]
The workaround described by @rramachand21 seems to work. Creating a `iisnode.yml` file and adding the line `debuggerExtensionDll: iisnode-inspector.dll` allows the debugger to appear.  I tried this using the `express` sample application that is included with iisnode.

**Comment by Siafu** [comment]
I tried it in the web.conf with IIS 7.5 and it didn't work. I'll revisit later today.

**Comment by dsbudiac** [comment]
Might not be the issue in your case, but I had the same symptoms when the app pool didn't have write permissions for the project directory.

**Comment by Siafu** [comment]
I created the iisnode.yml file and added debuggerExtensionDll: iisnode-inspector.dll to it. I now get the following error. Anyone able to get this working with IIS 7.5 

![image](https://cloud.githubusercontent.com/assets/632024/10229360/ce8becec-6845-11e5-9ea6-17fa331fbbfe.png)

**Comment by sagitsofan** [comment]
any new?

**Comment by rramachand21** [comment]
As a workaround for now, you can set debuggerExtensionDll="iisnode-inspector.dll" in the iisnode config to use the old node inspector because the old node inspector does not use websockets.

**Comment by msft-shahins** [comment]
@rramachand21 iisnode remote debugging on azure web apps is broken. Is there a work around or fix for this? I am keep getting the following error navigating to the iisnode debugger path: 

![image](https://user-images.githubusercontent.com/17562300/32685324-ad86cc48-c643-11e7-9cb4-d7d5ffeb6f3f.png)

I also tried using the workaround you mentioned in your comment and keep hitting the same error as https://github.com/tjanczuk/iisnode/issues/388#issuecomment-144804723
