### ISSUE TITLE
Issue installing from Web Platform Installer

### ISSUE THREAD

**Issue by cb55555** [tjanczuk/iisnode#401]
I keep getting an error, and it appears to be a 32-bit vs. 64-bit issue.

Here's the screenshot:

![Screenshot](http://i.imgur.com/ORpQ0kg.png)

**Comment by rcdmk** [comment]
As an alternative that worked for me, you can create a symbolic link on installation and delete it later:

1. Open a command line prompt as Administrator
2. Type in `mklink /D "c:\program files (x86)\nodejs" "c:\program files\nodejs"` and press <kbd>ENTER</kbd>
3. Run the installation on WPI
4. Back to the command prompt, type in `rmdir "c:\program files (x86)\nodejs" and press <kbd>ENTER</kbd> to delete the link

> Note: the syntax for `mklink` command is: `mklink [flag] [destination path] [origin path]`
> Where `[flag]` here is `/D` to make a directory link
