### ISSUE TITLE
Question: What's the difference between the "Core" and "Full" versions?

### ISSUE THREAD

**Issue by NoelAbrahams** [tjanczuk/iisnode#408]
Hi,

I was using the full version at 2.7, and wanted to upgrade. But just noticed that the size has gone up from 1.98 MB to 12.8 MB for the x64 full version.

We just want the plain-vanilla functionality - nothing fancy. Will the core version do?

Thanks.

**Comment by rramachand21** [comment]
You cannot have 2 iisnode sections in the web.config. Is this still an issue. please reopen if needed.

**Comment by NoelAbrahams** [comment]
Thanks for the prompt response! :smile:  I can't even remember what I did to get this fixed.
