### ISSUE TITLE
iisnode and global modules?

### ISSUE THREAD

**Issue by SparserLogic** [tjanczuk/iisnode#413]
I'm trying to figure out how to get iisnode running with IIS handling kerberos and this module: https://github.com/topcloud/loadbalancer running as a load balancer.

The issue being, the NPM module needs to be run in "global" command line mode. Is there a currently supported way to run a global module through iisnode?

**Comment by rramachand21** [comment]
Why dont you use ARR to do the load balancing?

**Comment by SparserLogic** [comment]
Because it doesn't work with Authentication.

You can close this ticket. I went with a different method in the end.

**Comment by rramachand21** [comment]
ok, http://blogs.msdn.com/b/chiranth/archive/2014/04/17/setting-up-kerberos-authentication-for-a-website-in-iis.aspx & http://blogs.msdn.com/b/asiatech/archive/2013/06/04/a-quick-solution-when-windows-authentication-is-required-on-backend-web-server-for-arr-scenario.aspx have some information on this.

**Comment by SparserLogic** [comment]
Appreciated!
