### ISSUE TITLE
Win7 IIS App Pool stops when trying to view hello world or static HTML through iisnode 0.2.16

### ISSUE THREAD

**Issue by raykendo** [tjanczuk/iisnode#414]
After installing 0.2.16 x64bit on Windows 7 desktop with IIS, I tried to launch the hello world applications. Application Pool for that process stops, and I receive an HTTP 503 error (Service Unavailable). Application Pool stops when I try to load either static html or Node.js apps. When I allowed for 32 bit applications, the same thing happened.

When using Dependency Walker, it found the following DLL files unavailable:
API-MS-WIN-APPMODEL-RUNTIME-L1-1-0.DLL
API-MS-WIN-CORE-WINRT-ERROR-L1-1-0.DLL
API-MS-WIN-CORE-WINRT-L1-1-0.DLL
API-MS-WIN-CORE-WINRT-ROBUFFER-L1-1-0.DLL
API-MS-WIN-CORE-WINRT-STRING-L1-1-0.DLL
API-MS-WIN-SHCORE-SCALING-L1-1-1.DLL
DCOMP.DLL
IESHIMS.DLL

Global Modules in applicationHost.config contains the following.

    &lt;add name="iisnode" image="%programfiles%\iisnode\iisnode.dll" preCondition="bitness64" /&gt;

**Comment by rramachand21** [comment]
please refer to this - http://stackoverflow.com/questions/17023419/win-7-64-bit-dll-problems
