### ISSUE TITLE
Crashes and ETIMEDOUT on Azure Websites

### ISSUE THREAD

**Issue by markusahlstrand** [tjanczuk/iisnode#415]
Hi, 

We have issues with short outages that we think is due to the node.js processes restarting. The strange part is that it hits multiple websites on separate web hosting plans on simultaneously making us think that this is an issue with the underlying storage or something similar. Found the following error in our logs which I find very strange. It seems to be looking for the index.html in the public folder which doesn't and shouldn't exist. Could this be due to a request coming in while the node.js process is restarting or are there any other valid cases when this could occur?

Anyone else experiencing short outages periodically on Azure Websites with node.js?

Message: ETIMEDOUT, stat 'D:\home\site\wwwroot\public\index.html'

**Comment by rramachand21** [comment]
Hi, whats your azure website name?

**Comment by markusahlstrand** [comment]
Hi Ranhith,

I'll send you the details of environment in an email.

Thanks,
Markus

**Comment by markusahlstrand** [comment]
We've been digging through the logs today and made a few interesting findings:
- All the instances rebooted within a second, which to me seems that there's some common resource that caused this issue.
- Other websites on separate web hosting plans rebooted simultaneously even though theres no common code or dependencies
- There's nothing in stdErr, which might indicate that it isn't node.js crashing.
- We get unhandled exceptions in the event-log which I assume originates from IIS or IISNode? See below for an example. Could it be that IISNode doesn't handle these malformed urls? 

Is there any other log where we could find more information about why the process restarted?

<Event>
<System>
<Provider Name="ASP.NET 4.0.30319.0"/>
<EventID>1309</EventID>
<Level>2</Level>
<Task>0</Task>
<Keywords>Keywords</Keywords>
<TimeCreated SystemTime="2015-01-27T13:31:14Z"/>
<EventRecordID>862297125</EventRecordID>
<Channel>Application</Channel>
<Computer>RD00155D801EA4</Computer>
<Security/>
</System>
<EventData>
<Data>3005</Data>
<Data>An unhandled exception has occurred.</Data>
<Data>1/27/2015 1:31:14 PM</Data>
<Data>1/27/2015 1:31:14 PM</Data>
<Data>147dc3fb6d774452bf9ad08c08e7a7af</Data>
<Data>2</Data>
<Data>1</Data>
<Data>0</Data>
<Data>/LM/W3SVC/1519092344/ROOT-8-130668372514783840</Data>
<Data>Full</Data>
<Data>/</Data>
<Data>D:\home\site\wwwroot\</Data>
<Data>RD00155D801EA4</Data>
<Data/>
<Data>5320</Data>
<Data>w3wp.exe</Data>
<Data>IIS APPPOOL\xxxxx</Data>
<Data>HttpException</Data>
<Data>
A potentially dangerous Request.Path value was detected from the client (*). at System.Web.HttpRequest.ValidateInputIfRequiredByConfig() at System.Web.HttpApplication.PipelineStepManager.ValidateHelper(HttpContext context)
</Data>
<Data>
https://xxxxx:443/redirectByUrl/tsknas/126"ivegotaprettyd*ck
</Data>
<Data>/redirectByUrl/tsknas/126"ivegotaprettyd*ck</Data>
<Data>90.144.213.227</Data>
<Data/>
<Data>False</Data>
<Data/>
<Data>IIS APPPOOL\xxxx</Data>
<Data>48</Data>
<Data>IIS APPPOOL\xxxxx</Data>
<Data>False</Data>
<Data>
at System.Web.HttpRequest.ValidateInputIfRequiredByConfig() at System.Web.HttpApplication.PipelineStepManager.ValidateHelper(HttpContext context)
</Data>
</EventData>
</Event>
