### ISSUE TITLE
io.js support?

### ISSUE THREAD

**Issue by mikeal** [tjanczuk/iisnode#416]
Got this question on Twitter and I didn't have an answer :)

**Comment by rramachand21** [comment]
you can run it by setting the nodeProcessCommandLine to iojs in the web.config or iisnode.yml file.

**Comment by tjanczuk** [comment]
In fact you can use iisnode to host any runtime that adheres to a simple behavioral contract: it establishes an HTTP listener on the port given to it via the PORT environment variable. Note that the "port" iisnode sets via the PORT environment variable is actually a named pipe name, not an integer. 

You can configure the executable iisnode spawns via the nodeProcessCommandLine property (https://github.com/tjanczuk/iisnode/blob/master/src/samples/configuration/iisnode.yml#L10-L13).

**Comment by ryanwmarsh** [comment]
:+1:

**Comment by queequac** [comment]
At least my version of iojs has also a node.exe (with iojs-logo) in its installation folder.
I guess in that case it makes no difference for iisnode anyhow.
