### ISSUE TITLE
Port 80 requires elevated privileges

### ISSUE THREAD

**Issue by robinkedia** [tjanczuk/iisnode#417]
Please advise -
iisnode encountered an error when processing the request.
HRESULT: 0x2
HTTP status: 500
HTTP subStatus: 1002
HTTP reason: Internal Server Error

You are receiving this HTTP 200 response because system.webServer/iisnode/@devErrorsEnabled configuration setting is 'true'.

In addition to the log of stdout and stderr of the node.exe process, consider using debugging and ETW traces to further diagnose the problem.

The last 64k of the output generated by the node.exe process to stderr is shown below:
Port 80 requires elevated privileges

**Comment by rramachand21** [comment]
Is your node app listening on process.env.PORT ?

**Comment by robinkedia** [comment]
I'm using this code
process.env.PORT  || 3000

**Comment by robinkedia** [comment]
I want to make it run on port 80 and not 3000

**Comment by robinkedia** [comment]
Can anyone help on these one?

**Comment by rramachand21** [comment]
iisnode and node.exe communicate over named pipes and therefore process.env.PORT is what you need to listen on which is a named pipe when you are using iisnode. Your iis site can be configured to listen on port 80.

**Comment by koistya** [comment]
@rramachand21 /all How to make a local request to Express.js route when http server is hosted on a named pipe? Or, is it a better way to figure out which port IISNode exposes and send HTTP request to that port instead? If so, how to find out which port IISNode is using?

**Comment by edrujo** [comment]
any update on this?

**Comment by luckysai1976** [comment]
I am also facing same problem, if any solution it will help.

**Comment by nystromb** [comment]
Try using sudo when starting your project

**Comment by scarvill91** [comment]
As as a general rule processes running without root privileges cannot bind to ports below 1024

**Comment by rramachand21** [comment]
@koistya iisnode runs within w3wp which listens to whatever Port you configure it to listen on via IIS. iisnode and node.exe communicate over named pipe. If your IIS site is listening on port 80 and you have configured iisnode for this site, requests coming in on port 80 will be handled by iisnode and then forwarded to node.exe over named pipe.

**Comment by sevenshadow** [comment]
I got to this page because I was receiving the same error (e.g. HTTP status: 500
HTTP subStatus: 1002).

I was deploying a node application to azure.  My root directory of my application bundled up it a /dist directory.

To solve this issue I had to change the settings in azure so that the 
Virtual applications and directories setting

"/" mapped to "site\wwwroot\dist"

Seems obvious after the fact, but previously I had been trying to configure the root directory in the server.js settings etc. of my code.  Hope this helps someone.

**Comment by aeciolevy** [comment]
@robinkedia I my case the IIS_IUSRS was not assigned to my application folder. Thus, I used the setupexamples to run and create a AppTool for my iisnode application to assign IIS_IUSRS with full control for that folder. It solved my problem.
