### ISSUE TITLE
IIS Win10 + iisnode = HTTP2.0 node enabled app?

### ISSUE THREAD

**Issue by molant** [tjanczuk/iisnode#418]
It looks like the next version of [IIS on Win 10 is going to support HTTP2.0](http://blogs.iis.net/nazim/archive/2014/10/29/http-2-for-iis-in-windows-10-technical-preview.aspx).
Does that mean that if I enable it and the browser doing the request supports it I will not have to do anything on my node application to be HTTP2 ready?

**Comment by rramachand21** [comment]
Yes - you will not need to do anything.
