### ISSUE TITLE
Handler "iisnode" has a bad module "iisnode" in its module list

### ISSUE THREAD

**Issue by akempe** [tjanczuk/iisnode#42]
HTTP Error 500.21 - Internal Server Error

I'm am getting this error on a clean download and install of iisnode-iis7-v0.1.7-x86.msi under Windows 7 x64 with VS2010 installed.

No matter how I tweak permissions, app pool settings etc, I keep getting this. 

Any ideas?

thanks, Andrew

**Comment by twobob** [comment]
for me it was updating to the latest version and allowing read/write permissions on the parent folder
