### ISSUE TITLE
Comparison with HttpPlatformHandler?

### ISSUE THREAD

**Issue by waynebloss** [tjanczuk/iisnode#420]
Hello,

Can anyone provide a comparison between iisnode and [the new HttpPlatformHandler for IIS](http://www.hanselman.com/blog/AnnouncingRunningRubyOnRailsOnIIS8OrAnythingElseReallyWithTheNewHttpPlatformHandler.aspx)?

Mainly I'd just like to know if iisnode is necessary or useful for doing things that HttpPlatformHandler cannot do.

Thank you.

**Comment by waynebloss** [comment]
Closing old issues that nobody responded to.

**Comment by Osmangazi** [comment]
https://learn.microsoft.com/en-us/answers/questions/254320/which-handler-is-preferred-to-host-golang-api-as-a

"[ajkuma](https://learn.microsoft.com/en-us/users/na/?userid=4dc8ff92-7149-40f5-8a3d-3fc58dfec77e)
16,941 Reputation points• Microsoft Employee
Feb 8, 2021, 10:19 PM
To benefit the community, summarizing the answer from our discussion above (via 'comments'):

For .net core use ASPNetCoreModulev2, for node js use iis node and for all other use HTTPPlatformHandler."
