### ISSUE TITLE
Allow multi wildcards for watchedFiles property

### ISSUE THREAD

**Issue by luca-moser** [tjanczuk/iisnode#426]
Hi Tomasz,
I want to be able to declare paths like `models\**\*.js` for watchedFiles in web.config since I don't want to enter each sub directory manually to the list of watched files. Currently only `*.js` is working. Using a wildcard directory entry like `models\**\*.js` crashes IISNode.

**Comment by donatasbacius** [comment]
+1

**Comment by dfoverdx** [comment]
+1

**Comment by dsbudiac** [comment]
+1

**Comment by rramachand21** [comment]
Please code this up in your java script code as every app wants different capability with watched files. You can watch files within your app however you want and then finally update one file that iisnode is looking for.

**Comment by ayyash** [comment]
You mean (for example): gulp watch server/**/*.js to recreate ./server.js? if there is nothing to update in that file, would iis still pick up the recreation and trigger a restart?

**Comment by mac2000** [comment]
JFYI: just went back from my _dynamic webpack entry point_ journey with some results https://github.com/mac2000/webpack-dynamic-entry-demo

hope it will help someone else also, in our case idea is that we have always running IIS web site which compiles requested file on the fly, so developer do not need to start and/or restart anything, just turn on PC and start coding and having fun

it is just to demonstrate one of possible ways how it can be done even without file watchers
