### ISSUE TITLE
The installer aborts on windows 10

### ISSUE THREAD

**Issue by scsouthw** [tjanczuk/iisnode#428]
I get an error that "IIS 7.x or later must be installed before iisnode installation."

My IIS version is 10.0.10041.0. Could the comparison [here](https://github.com/tjanczuk/iisnode/blob/33f224a90f673e00667e2b92ef699b00e3d10789/src/setup/iisnode-msi/iisnode.wxs#L53-L55) be broken somehow since the string `"10"` is less than `"7"`?

I tried changing the regsitry value for iiS major version to 9 but it didn't help: Computer\HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\W3SVC\Parameters\MajorVersion

**Comment by rramachand21** [comment]
Yes, I will fix this soon.

**Comment by rramachand21** [comment]
Fixed this. - please use 0.2.18

**Comment by sahaiabhi** [comment]
Dear Ranjith,

I am trying to install iisnode on windows 10, but it shown no progress during installation even after an hour.

Tried multiple version from your github post.

Could you please help me.
