### ISSUE TITLE
Windows auth user identity infomation

### ISSUE THREAD

**Issue by digitalsadhu** [tjanczuk/iisnode#429]
This question refers to windows integrated auth.

I understand that I can promote server vars such as AUTH_USER #87 but how would I get access to additional logged in user information such as the security group(s) they belong to?

I am currently toying with the idea of doing an LDAP query to windows auth server to get additional information about the user but would rather avoid the effort if possible...

thanks

**Comment by rentrop** [comment]
+1

**Comment by pr0gramar** [comment]
+1

**Comment by tjanczuk** [comment]
I don't think iisnode is the proper layer to address this issue. Such information should either be exposed by IIS, or the app should be in charge of obtaining this data.
