### ISSUE TITLE
logging causing continual startup of new node.exe processes

### ISSUE THREAD

**Issue by jeremydiviney** [tjanczuk/iisnode#442]
for 1 particular project.... if i set logDirectory to anything that is within the parent path of my node application, it seem to cause constant spawing of new node.exe processes when a page request comes in.  Additionally, I get huge numbers of log files appearing in my iisnode log directory.  It is behaving as though I had my log files set to be watched, so each update to the log file is causing a recycle of the worker process.

Howerver, my watched file is as follows: watchedFiles="web.config;*.js"

If I set logDirectory="../iisnode"  or set loggingEnabled="false"
this issue goes away the app performs normally.

Using windows server 2012

**Comment by rramachand21** [comment]
This means that your application pool do not have permissions to write to ../iisnode
