### ISSUE TITLE
iisnode fails to return a large JSON response

### ISSUE THREAD

**Issue by kirilyuro** [tjanczuk/iisnode#444]
I have an API call to a node service which returns a large (about 7MB) JSON response. I can see the request handled successfully on the server (it creates the response data and calls the express res.json() method). The client receives a 200 OK and the correct response headers on the request (including the ~7MB Content-Length header). However, the response body never gets back to the client. IIS resets the connection when it times out, and the client gets a net::ERR_CONNECTION_RESET error.

I have tried changing the IIS connection timeout from the default 2min to as high as 10min, and it still fails (the client gets the connection reset error after 10min, accordingly).

If I return only a small portion of the 7MB data, everything works fine.

I am using iisnode 0.1.14 on IIS 7.5 with NodeJS v0.12.7. The OS is Windows 7 (SP1). All are 64-bit.

**Comment by rramachand21** [comment]
Please use iisnode 0.2.18 (or the latest) and also make sure your application returns 7MB json when you directory run with node.exe and not use iisnode.

**Comment by kirilyuro** [comment]
Thanks, I'll try that. 
From what I see, the latest version in this repo is 0.1.14, and in the Azure repo it's 0.2.2. 
Could you please point me to the most up-to-date repo of iisnode, containing the version you mentioned?

**Comment by rramachand21** [comment]
https://github.com/tjanczuk/iisnode/releases - select one of the *full* versions.
