### ISSUE TITLE
ISSnode not able to reconnect to MongoDB on Azure Webapps

### ISSUE THREAD

**Issue by manoj97738** [tjanczuk/iisnode#445]
Its weird that ISSNODE is preventing re-connection to mongodb replica set in the following scenario.

1. Primary server goes down and secondary server is set as primary server, at this period the connection with the mongodb and node.js app on IISNODE is working but when primary is up and secondary goes down, the ISSNODE is preventing re-connection to mongodb.

I tried the same scenario without iisnode on my local machine, it works fine.

Please suggest which options to set in config of IISNODE to avoid this or is there any other configuration i need to set.

1 # The optional iisnode.yml file provides overrides of   
 2 # the iisnode configuration settings specified in web.config.  
 3
 4 node_env: production  
 5 nodeProcessCommandLine: "c:\program files\nodejs\node.exe"  
 6 interceptor: "c:\program files\iisnode\interceptor.js"  
 7 nodeProcessCountPerApplication: 1  
 8 maxConcurrentRequestsPerProcess: 1024  
 9 maxNamedPipeConnectionRetry: 24  
10 namedPipeConnectionRetryDelay: 250  
11 maxNamedPipeConnectionPoolSize: 512  
12 maxNamedPipePooledConnectionAge: 30000  
13 asyncCompletionThreadCount: 0  
14 initialRequestBufferSize: 4096  
15 maxRequestBufferSize: 65536  
16 watchedFiles: *.js;iisnode.yml  
17 uncFileChangesPollingInterval: 5000  
18 gracefulShutdownTimeout: 60000  
19 loggingEnabled: true  
20 logDirectory: iisnode  
21 debuggingEnabled: true  
22 debuggerPortRange: 5058-6058  
23 debuggerPathSegment: debug  
24 maxLogFileSizeInKB: 128  
25 maxTotalLogFileSizeInKB: 1024  
26 maxLogFiles: 20  
27 devErrorsEnabled: true  
28 flushResponse: false  
29 enableXFF: false  
30 promoteServerVars

**Comment by rramachand21** [comment]
THere is nothing in iisnode that would prevent the reconnect. Please check your application error logs to see what error your application is throwing when the connection fails.
