### ISSUE TITLE
nodeProcessCommandLine should be allowed to be a relative path

### ISSUE THREAD

**Issue by MrHacky** [tjanczuk/iisnode#448]
This greatly simplifies deployment for us on our test servers, where a simple unzip of our release package is the only step needed.

See #356 for an implementation. (though that only works if the path starts with '.' as i didn't see an easy way to check if a path is relative...)

**Comment by rramachand21** [comment]
We are not going to support this due to security reasons.

**Comment by MrHacky** [comment]
Okay... could you please explain what those reasons are?

**Comment by RamIdeas** [comment]
Security reasons? Surely being able to specify any .exe anywhere on the file system is more of a security concern

**Comment by ciaranj** [comment]
^^ But the current support already allows you to 'specify any .exe anywhere on the file system', how is specifying a relative path in the config any worse security-wise than being able to specify any absolute path?

**Comment by olee** [comment]
Would like some clarification on this as well?
Where's the problem allowing a path relative to the current directory only like `bin\node.exe`?
This would work then on different machines as well.
