### ISSUE TITLE
Cannot run Meteor 1.1 app with IISNode

### ISSUE THREAD

**Issue by ericterpstra** [tjanczuk/iisnode#449]
I've been trying to get a Meteor app working with iisnode for days with no luck.  The app works fine when starting from the command line (with `set PORT=3000 && node main.js`), but fails when setting up a site in IIS with iisnode.

My environment:
* Windows Server 2012 R2 64-bit
* IIS 8.5 (with URL Rewrite, Websockets, and many more modules)
* IISNode 0.2.18 x64
* Node.js 0.12.7 64-bit
* Meteor 1.1.0.4 app exported with `meteor build` which creates a node.js application

Setup:
* Created a site in IIS Manager (myapp.mydomain.com). Node app is in the root of the folder.
* Placed `web.config` file in root of app folder. See below for current web.config
```xml
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
	<system.web>
		<compilation batch="false" />
	</system.web>
	<system.webServer>
		<handlers>
		  <add name="iisnode" path="main.js" verb="*" modules="iisnode" />
		</handlers>
	<rewrite>
		<rules>
			<rule name="LogFile" patternSyntax="ECMAScript" stopProcessing="true">
				<match url="iisnode" />
			</rule>
			<rule name="myapp">
				<match url="/*" />
				<action type="Rewrite" url="main.js" />
			</rule>
		</rules>
	</rewrite>
	<webSocket enabled="false" />
	</system.webServer>
</configuration>
```

Navigating to http://myapp.mydomain.com gives this error:
```text
iisnode encountered an error when processing the request.

HRESULT: 0x2
HTTP status: 500
HTTP subStatus: 1001
HTTP reason: Internal Server Error
You are receiving this HTTP 200 response because system.webServer/iisnode/@devErrorsEnabled configuration setting is 'true'.

In addition to the log of stdout and stderr of the node.exe process, consider using debugging and ETW traces to further diagnose the problem.

The node.exe process has not written any information to stderr or iisnode was unable to capture this information. Frequent reason is that the iisnode module is unable to create a log file to capture stdout and stderr output from node.exe. Please check that the identity of the IIS application pool running the node.js application has read and write access permissions to the directory on the server where the node.js application is located. Alternatively you can disable logging by setting system.webServer/iisnode/@loggingEnabled element of web.config to 'false'.
```

The entry point of a built Meteor app is `main.js` which is a small file that calls the Meteor bootstrap.  I placed `console.log(process.env.PORT)` at the top of the file to see if iisnode was routing correctly.  After navigating to the app's URL, an iisnode folder was created with a log file containing a single line: `\\.\pipe\462369a1-321e-413d-86e5-8ba474d5a9f3`.  I can also view the log file(s) by going to `http://myapp.mydomain.com/iisnode`.  My ETW output for a single request can be found at: https://gist.github.com/ericterpstra/b26ad82e070173e474df 

So iisnode and IIS works, and my Meteor app works, but they don't work together, and I'm not sure why.  I've seen evidence online that Meteor supports names pipes ([here](https://github.com/meteor/meteor/issues/4413) and [here](https://git.zserve.co.uk/meteor/meteor/commit/6c1ff64789524ee890a9ae84c92fdebf868faf5a)), and that others have gotten Meteor working with IISNode ([here](http://stackoverflow.com/a/27377523/189551) and [here](http://www.anuragbhandari.com/2012/11/hosting-meteor-js-app-in-iis/)). 

Any advice is welcome. Please let me know if I can provide further information.  Thanks.

**Comment by rramachand21** [comment]
meteor assumes the process.env.PORT to be a number and uses parseInt on the process.env.PORT  -- you will need to remove this parseInt function for it to work because iisnode sets process.env.PORT to a named pipe. We have filed a bug against meteor for them to remove the parseInt from their code - https://github.com/meteor/meteor/issues/4413

**Comment by rramachand21** [comment]
Please let me know if this worked.

**Comment by dotnetwise** [comment]
Still nothing?

**Comment by ericterpstra** [comment]
Yes, altering `/bundle/programs/server/packages/webapp.js` in the built/deployed app works, but I'm hesitant to use it as a permanent solution because it requires altering core Meteor files.  

If I alter the file **before** I run the build command, the change will get overwritten when I update the Meteor framework for a security patch or point release.  If I leave the core as-is, and alter the file **after** the build, then I have to make the correction every time I deploy, or edit the file as part of a deploy script (which seems hacky and brittle over the long term).  

Essentially, though, this is an issue with Meteor and not IISNode. I will close this issue, and keep an eye on https://github.com/meteor/meteor/issues/4413

Thanks for your attention, I appreciate it.  Hopefully Meteor will address this issue soon and we will all be able to use IISNode.
