### ISSUE TITLE
We are getting some initialization error in starting the node in Windows Server 2012. we tried permission and adding node path in the config still not working.

### ISSUE THREAD

**Issue by lalitrhombus** [tjanczuk/iisnode#457]
here is the xml file clip.may be it can help to figure out the problem.

![image](https://cloud.githubusercontent.com/assets/14086791/10966763/cf205e7a-83db-11e5-97d6-5c91c36cca8f.png)
i successfully integrated it on local windows flow.but only getting problem in windows server.

**Comment by rramachand21** [comment]
You will need to check if node.exe threw any exceptions in this case.
