### ISSUE TITLE
Documentation needs update?

### ISSUE THREAD

**Issue by alvarotrigo** [tjanczuk/iisnode#459]
> Open WebMatrix, choose “Site from folder”, enter %localappdata%\iisnode\www, start the site, and play with the iisnode samples, or

I downloaded the latest Web Matrix and I was not able to find the “Site from folder” option on it. 
I guess its called "Open" now? Then "Folder" ?

![webmatrix](https://cloud.githubusercontent.com/assets/1706326/11240043/7a051eba-8de7-11e5-9210-28c7fd0b5b1e.PNG)

Also, the directory `%localappdata%\iisnode\www` doesn't exist. Are we suppose to create the folders `iisnode` and `www` ?
Or... should we point instead to `C:\Program Files (x86)\iisnode\www` where the examples we installed are?

**Comment by rramachand21** [comment]
%localappdata%\iisnode\www is setup when you run setupsamples.bat manually.
