### ISSUE TITLE
HTTP status 500.1001

### ISSUE THREAD

**Issue by Siafu** [tjanczuk/iisnode#464]
HRESULT: 0x2
HTTP status: 500
HTTP subStatus: 1001
HTTP reason: Internal Server Error

I get the following error whenever I launch my application for the first time. This is fixed by just refreshing the browser but I would love to know whats causing it. I followed the initial troubleshooting advice and ran the etw.bat for the trace. I looked over the logs and didn't see any errors. Not sure what I should be even looking for there. 

My environment is as follows.
IIS 7.5 windows server 2008 R2
IISNODE 32 bit how to find the version ?
Load balanced with another server with the same setup.
webconfig
<configuration>
    <appSettings>
        
        <add key="virtualDirPath" value="/claimcheck" />
    </appSettings>
    <system.webServer>
        
        <staticContent>
            
        </staticContent>
        <modules runAllManagedModulesForAllRequests="false" />

        <iisnode node_env="build" nodeProcessCountPerApplication="1" maxConcurrentRequestsPerProcess="1024" maxNamedPipeConnectionRetry="100" namedPipeConnectionRetryDelay="250" maxNamedPipeConnectionPoolSize="512" maxNamedPipePooledConnectionAge="30000" asyncCompletionThreadCount="0" initialRequestBufferSize="4096" maxRequestBufferSize="65536" uncFileChangesPollingInterval="5000" gracefulShutdownTimeout="60000" loggingEnabled="true" logDirectory="iisnode" debuggingEnabled="true" debugHeaderEnabled="false" debuggerPortRange="5058-6058" debuggerPathSegment="debug" maxLogFileSizeInKB="128" maxTotalLogFileSizeInKB="1024" maxLogFiles="20" devErrorsEnabled="true" flushResponse="false" enableXFF="false" promoteServerVars="LOGON_USER" configOverrides="iisnode.yml" watchedFiles="web.config;*.js" nodeProcessCommandLine="C:\Program Files\nodejs\node.exe" />

        <handlers>
            
            <add name="iisnode" path="iisnode.js" verb="*" modules="iisnode" />
            
            
        </handlers>
        <rewrite>
            <rules>
                
                <rule name="NodeInspector" patternSyntax="ECMAScript" stopProcessing="true">
                    <match url="^app.js\/debug[\/]?" />
                </rule>

                
                <rule name="StaticContent" patternSyntax="Wildcard">
                    <action type="Rewrite" url="public/{R:0}" logRewrittenUrl="true" />
                    <conditions>
                        <add input="{REQUEST_FILENAME}" matchType="IsFile" negate="true" />
                    </conditions>
                    <match url="*.*" />
                </rule>
                
                <rule name="DynamicContent">
                    <conditions>
                        <add input="{REQUEST_FILENAME}" matchType="IsFile" negate="True" />
                    </conditions>
                    <action type="Rewrite" url="iisnode.js" />
                </rule>
                <rule name="SocketIO" patternSyntax="ECMAScript">
                    <match url="socket.io.+" />
                    <action type="Rewrite" url="iisnode.js" />
                </rule>
            </rules>
        </rewrite>
        <directoryBrowse enabled="false" />

    </system.webServer>
</configuration>

**Comment by Siafu** [comment]
I'm closing my issue as it think it relates to the issue posted here. https://github.com/tjanczuk/iisnode/issues/323

**Comment by yusuf987** [comment]
try to listen on "process.env.PORT" instead any hard coded nomber
like
instead
```

http.listen(3000, function() {
    console.log('listening...');
 });
```
try to use

```

http.listen(process.env.PORT, function() {
    console.log('listening...');
 });
```
