### ISSUE TITLE
High latency on streaming

### ISSUE THREAD

**Issue by markusahlstrand** [tjanczuk/iisnode#465]
Not sure if this is related to iisnode or if it's a configuration issue in iis.

We're building a service that serves chunks of audioFiles which works great when running node directly on windows. When we're hosting it via iis/iisnode we get a TTFB of 4-6 seconds compared to about 1 second running straight on windows. Checking the logs and the performance counters it seems that the node process returns the bytes immediately so we think that it's getting buffered somewhere on the way out.

We tried to disable all caches using the following setting in iisnode.yml:
flushResponse: true  
And the following settings in web.config:
```
<configuration>
    <system.webServer>
        <handlers>
            <remove name="ISAPI-dll" />
            <add name="ISAPI-dll" path="*.dll" verb="*" type="" modules="IsapiModule" scriptProcessor="" resourceType="File" requireAccess="Execute" allowPathInfo="true" preCondition="" responseBufferLimit="0" />
            <add name="iisnode" path="app.js" verb="*" modules="iisnode" />
        </handlers>
```

Are there any other buffers that can be disabled or is there anything else that can cause this behaviour? Is there a way to determine if the buffering is taking place in iis or iisnode?

Thanks,
Markus

**Comment by rramachand21** [comment]
Taking a look at this

**Comment by rramachand21** [comment]
I setup your repro https://github.com/markusahlstrand/streamsPerfTest and i am not able to repro the issue on my local machine - Whats your environment?

**Comment by rramachand21** [comment]
Also, &lt;attribute name="initialRequestBufferSize" type="uint" defaultValue="4096"/&gt;
    &lt;attribute name="maxRequestBufferSize" type="uint" defaultValue="65536"/&gt; -- Try to modify these to suit your application.

**Comment by markusahlstrand** [comment]
Thanks for taking a look at this.

I've tested on windows 10 and on Windows Server 2012 R2. Might not have the best connection at my current location, but running on iisnode I get a latency of 4-10 seconds. Running on straight node the response time is 400 ms (same server).

Got the same repo deployed to azure websites (http://acast-tmp.azurewebsites.net/test.mp3) and get about 900 ms response time. The source mp3-file is stored on blob storage so I would expect the latency to be a lot lower on azure compared to my local server.

For our real application which is a bit more complicated we get about 4 seconds latency on azure compared to 400 ms on Aws (nginx).

**Comment by rramachand21** [comment]
Disable IIS bufferring by setting the responseBufferLimit to 0 

<add name="iisnode" path="app.js" verb="*" modules="iisnode"  responseBufferLimit="0" />

There is a setting called flushResponse in iisnode, but this setting when enabled takes effect i.e flushes responses only in case of chunked transfer encoding OR when content-length is 0.
