### ISSUE TITLE
Two nodejs sites dont run in same IIS

### ISSUE THREAD

**Issue by bdcamara** [tjanczuk/iisnode#466]
I add two sites nodejs in my IIS, but one of then show error 500, boths are using the same IISnode framework. Exist some way to fix it?

**Comment by atom0s** [comment]
Are you certain the 2nd sites configuration and permissions are properly set?

**Comment by rramachand21** [comment]
Please give more details or else it becomes very difficult to answer :) -- Please paste your web.config of both sites, check your application pool permissions. You could enable devErrorsEnabled and check the win32 error code.
