### ISSUE TITLE
IIS has stopped by iisnode 

### ISSUE THREAD

**Issue by rrasheli** [tjanczuk/iisnode#468]
Hi,

My iis stopped by iisnode. I look at the Event Viewer Application logs and that logged this error:

The Module DLL C:\Program Files (x86)\iisnode\iisnode.dll failed to load.  The data is the error.

When I go to the program files and look at the Security tab in properties, in Advanced Security Settings for iisnode "psaadm" and "psacln" Type are Deny.

I change Deny to Allow but after some day that back to Deny.

Note: When that Type or access is Deny I get error: 503 error, service unavailable.

Are you have any solution for my problem?

**Comment by atom0s** [comment]
There is a closed issue here with the same report where the user solved their own issue:
https://github.com/tjanczuk/iisnode/issues/267
