### ISSUE TITLE
Activation latency and 500 for node app hosted as Azure Website

### ISSUE THREAD

**Issue by royfk21** [tjanczuk/iisnode#472]
Hi,

We have a microservices application based on NodeJS and ExpressJS that's hosted as an Azure Website (being served by IISNODE). Once in a while, looking at the pattern, especially after a long period of inactivity, any  of the service when invoked, stops responding or takes considerable amount of time to respond, utimately resulting in 500. If the app is restarted from azure portal, everything works fine.

Version of Node: 0.10.29
IISNODE: 0.2.20 

Note: Azure Website is already using AlwaysOn feature.

Came across one of the suggestions on application initialization to reduce activation latency 
http://tomasz.janczuk.org/2013/07/application-initialization-of-nodejs.html

The above article talks about changing settings at IIS level and applicationHost.config with preloadEnabled. However, this is not something that we can control at Azure Website level due to limited access as part of the hosting.

We could try increasing the value of maxNamedPipeConnectionRetry and/or namedPipeConnectionRetryDelay but any other suggestions/ideas would be helpful.

Thanks,
Roy

**Comment by atom0s** [comment]
Check out these links for setting up App Initialization on Azure:
http://fabriccontroller.net/iis-8-0-application-initialization-module-in-a-windows-azure-web-role/
http://ruslany.net/2015/09/how-to-warm-up-azure-web-app-during-deployment-slots-swap/

**Comment by rramachand21** [comment]
increasing the value of maxNamedPipeConnectionRetry and/or namedPipeConnectionRetryDelay should help. If you have lots of files in node modules, please try to instlal them using npm3 as it results in flat files instead of nested structure and that would save some cold start time. If possible profile your application to see where the time is being spent.
