### ISSUE TITLE
Does iisnode support the 4.2.x nodejs?

### ISSUE THREAD

**Issue by ejzhang** [tjanczuk/iisnode#478]
Now nodejs has been released 4.2.x LTS, does iisnode support it?

**Comment by doubletaketech** [comment]
What is answer to this?

**Comment by LoganElliott** [comment]
@ejzhang @doubletaketech I just got it working using IIS8(with Web Sockets) and Node v4.4.2

**Comment by rramachand21** [comment]
It does work. If it doesnt work, please let me know the details of the exceptions or errors you are seeing.
