### ISSUE TITLE
<iisnode watchedFiles="..." /> does not allow parent directory ("..") or current directory (".")

### ISSUE THREAD

**Issue by dfoverdx** [tjanczuk/iisnode#480]
When `watchedFiles` is set to include a path to a parent directory, IIS doesn't know what to do with the web.config file, and all requests return nothing (not even an error).

This is matters to me because of my directory structure (obviously).  I want to reset IIS when my `packages.json` file is refreshed.  My files/directories look like:

    /inetpub/noderoot/web.config
    /inetpub/noderoot/packages.json
    /inetpub/noderoot/server/node.exe
    /inetpub/noderoot/server/node.exe.config
    /inetpub/noderoot/server/<other server files including server.js>

and my `web.config` has (or would, if it worked)

    <iisnode 
          nodeProcessCommandLine="c:\inetpub\noderoot\server\node.exe"
          watchedFiles="<watched files relative to \server>;..\packages.json" />

**Comment by dpolivy** [comment]
See https://github.com/tjanczuk/iisnode/issues/257 for details. This isn't supported.
