### ISSUE TITLE
HTTP 500 error - 1013 substatus

### ISSUE THREAD

**Issue by lgyeresi** [tjanczuk/iisnode#481]
I am running iisnode 0.2.18 on Windows Server 2012 R2 (IIS 8.5) with Node.js 5.5.0. I am able to run the sample applications, but anything else I run returns:

iisnode encountered an error when processing the request.

HRESULT: 0x6d
HTTP status: 500
HTTP subStatus: 1013
HTTP reason: Internal Server Error

I can copy the sample folders under wwwroot, convert it to an Application in IIS and I can run the hello.js from helloworld without any problem.

However, if I try to create a new folder under wwwroot, and place a hello.js with the exact same contents as the original hello.js under the new folder, and it will return the http 500 error.

Ultimately, what I'm trying to do is create a node.js folder under wwwroot, and inside of this node.js folder, I want subfolders, each of them containing a simple node application. I want to be able to reach the node applications via http://iis/node.js/project1/app.js, http://iis/node.js/project2/app.js, etc.

Here's what I've tried so far to troubleshoot:
- assign full control over wwwroot to IIS_IUSRS
- assign permissions using icacls
- ran ETW trace. No real useful info there.
- creating new application pool for node applications
- running the application pool under different user (Local System, etc)
- downgrading Node.js to 4.2.6
- setting up IIS on an entirely new server. Same exact issue.

Throughout my troubleshooting, the only constant that has remained has been iisnode. Any other suggestions that I can try?

**Comment by rramachand21** [comment]
0x6d is pipe busy -

**Comment by rramachand21** [comment]
You will need to increase the NODE_PENDING_PIPE_INSTANCES setting of node.exe to a higher number. This setting controls the concurrent requests that node.exe handles over named pipes. By default this value is 4 which is pretty small. I will be releasing a newer version of iisnode that automatically sets this to a higher number.

**Comment by rramachand21** [comment]
Please Use iisnode v0.2.21 -- This one has the increased NODE_PENDING_PIPE_INSTANCES setting which should resolve the pipe busy errors. If you are still getting errors, then it could be an app issue where the app is not responding to requests soon enough.
