### ISSUE TITLE
Setup issue, iisnode for iis 7.x (x64) full -- Error 1722.

### ISSUE THREAD

**Issue by mberrueta** [tjanczuk/iisnode#484]
Hello, 

I tried several versions 1.18 to 2.2 and I get the same issue in all the setup. 

Is a windows server 2012 R2 , without any service pack. 

I intall node, urlrewrite and the redistribuable  package .

Error is: 
Product: iisnode for iis 7.x (x64) full -- Error 1722. There is a problem with this Windows Installer package. A program run as part of the setup did not finish as expected. Contact your support personnel or package vendor.  Action AddIisnodeModuleRegistration, location: E:\, command: C:\Windows\system32\inetsrv\appcmd.exe install module /name:iisnode /image:"C:\Program Files\iisnode\iisnode.dll" /preCondition:bitness64 /commit:apphost 

there is a way to install without the msi ?or try to install with more debug information ?

**Comment by nearwood** [comment]
I'm having a similar issue. WS2012 R2, have Node installed already.

Full and core x64 installers for v0.2.18 seem to be broken, with this error in the event log:

`Product: iisnode for iis 7.x (x64) full -- Error 1720. There is a problem with this Windows Installer package. A script required for this install to complete could not be run. Contact your support personnel or package vendor.  Custom action AddIisnodeSection script error -2146827859, Microsoft JScript runtime error: Automation server can't create object Line 5, Column 5,  `

**Comment by mberrueta** [comment]
I solve my issue, uninstalling all, and reinstalling.

I didn't use the web installer, I install offline
