### ISSUE TITLE
503:  iisnode was unable to establish named pipe connection to the node.exe process because the named pipe server is too busy

### ISSUE THREAD

**Issue by NareshBanala** [tjanczuk/iisnode#487]
@rramachand21 
I am getting 503 'iisnode was unable to establish named pipe connection to the node.exe process because the named pipe server is too busy' error intermittently. 

Below are log from ETW.
{35529877-07E5-4806-8853-BA41766CF71D}: iisnode scheduled a retry of a named pipe connection to the node.exe process 

{EAB5DDBF-5420-4EFD-A253-EB22DC815A0D}: iisnode was unable to establish named pipe connection to the node.exe process because the named pipe server is too busy

Below are environment details:
 Windows Server 2012 R2 64 bit
IISnode v0.2.11.0
node.exe(NodeJs) 64 bits 4.4.0

**Comment by rramachand21** [comment]
If you have too many requests flowing through, there is limit on the number of concurrent requests node.exe can handle over named pipes. By default this value is 4. In the latest version of iisnode, iisnode passes an env variable NODE_PENDING_PIPE_INSTANCES to node.exe to increase this value  to 50.

**Comment by OZZlE** [comment]
> NODE_PENDING_PIPE_INSTANCES

where do you change that? In web.config? don't see it in any example

**Comment by OZZlE** [comment]
I tried

    <iisnode node_env="%node_env%" nodeProcessCommandLine="node.exe --no-deprecation --no-warnings NODE_PENDING_PIPE_INSTANCES=5000"/>

in web.config doesn't help
