### ISSUE TITLE
setupsample.bat is not included iniisnode-core-v0.2.18-x64

### ISSUE THREAD

**Issue by toneware** [tjanczuk/iisnode#491]
I found the source for [setupsample.bat](https://github.com/tjanczuk/iisnode/blob/master/src/scripts/setupsamples.bat), but it's five years old. Are there any updates and/or dependencies that I need to be aware of, or can I just run it as is?

I've installed iniisnode-core-v0.2.18-x64 on a Windows Server 2012 R2 box, running IIS 8.5 and node.js 5.10 x64, FWIW.

I could probably live without the samples, but it looks like they do some important config stuff, too. As you can probably tell, I'm totally new to node.js and iisnode, so I'm not yet sure if I need to mimic the procedure set forth in the setupsamples batch file.

**Comment by rramachand21** [comment]
There are no updates to setupsample.bat. You can use it as is and it works.
