### ISSUE TITLE
Status 500 with express app in IIS 8

### ISSUE THREAD

**Issue by jairoGilC** [tjanczuk/iisnode#501]
Hi,

I am try to deploy my nodeJS app with Exppress framework running by port 3000 `var port = normalizePort(process.env.PORT || '3000');`  but  get the following error:

     HRESULT: 0x2
     HTTP status: 500 
     HTTP subStatus: 1001 
     HTTP reason: Internal Server Error`

     You are receiving this HTTP 200 response because system.webServer/iisnode/@devErrorsEnabled configuration setting is 'true'.

    In addition to the log of stdout and stderr of the node.exe process, consider using debugging and ETW traces to further diagnose the problem.

    The node.exe process has not written any information to stderr or iisnode was unable to capture this information. Frequent reason is that the iisnode module is unable to create a log file to capture stdout and stderr output from node.exe. .......`

I use this [question](http://stackoverflow.com/questions/14934006/iis-iusrs-and-iusr-permissions-in-iis8) to solve the permission problem, but with this only generate the stdout files.

can by a different problem that permission?

**Comment by jairoGilC** [comment]
I can find the error, the problem is that the web.config file is different if you are using express 4, her and [example](http://tstrimple.com/express-4-azure-websites/) that work form me

**Comment by ryanvgates** [comment]
@jairoGilC can you copy the content from the link here? It is no longer working.

**Comment by adambarthelson** [comment]
+1
