### ISSUE TITLE
HTTP Error 500.19 - Internal Server Error

### ISSUE THREAD

**Issue by Cecildt** [tjanczuk/iisnode#52]
Hi,

I got the below error when I set up everything on 64x Win 7 machine.

Module  IIS Web Core
Notification    BeginRequest
Handler Not yet determined
Error Code  0x80070021
Config Error    This configuration section cannot be used at this path. This happens when the section is locked at a parent level. Locking is either by default (overrideModeDefault="Deny"), or set explicitly by a location tag with overrideMode="Deny" or the legacy allowOverride="false".
Config File \?\C:\Program Files\iisnode\www\helloworld\web.config

To fix this you need to make sure the Handler Mappings in Feature Delegation is set to Read/Wite.
After that you need to reset delegation.

To access this area open IIS Manager select the root node (Server Name). In the middle you will find the Feature Delegation option. Set the Handler Mappings to Read/Write. On the right hand click Custom Site Delegation. Select the site under which Node is running and click the action Reset All Delegation.

Hope this helps you!

**Comment by jamietre** [comment]
FYI - on a completely clean install of IIS 8.5 on Windows Server 2012 R2, I had this problem, fixed as OP suggests.

**Comment by fredericklin** [comment]
+1 fixed for me too

**Comment by alvarotrigo** [comment]
> To fix this you need to make sure the Handler Mappings in Feature Delegation is set to Read/Wite.
> After that you need to reset delegation.

If I reset the delegation then it turns back to "Read only". Therefore I set it to "Read/Write" and **I didn't reset all delegation** contrary as you said.

**Comment by alvarotrigo** [comment]
+1 This should be in the docs.

**Comment by jairoGilC** [comment]
I get this error with the example in setupsamples.bat. This solution work for all page except urlrewrite and express but the error code change to 0x800700d

**Comment by aeciolevy** [comment]
I was trying to fix the problem related to staticfolder (express.static) and I got this problem. I could not solve with this instructions.

**Comment by ves-krd** [comment]
@jairoGilC Download the URL rewrite module for IIS, that should solve those folders.

**Comment by rsalunga29** [comment]
Thank you for this! Cheers! 🍻

**Comment by manhnguyenquoc** [comment]
it works for me, thank you very much.

**Comment by Pattapee** [comment]
> ![feature](https://user-images.githubusercontent.com/1706326/27696646-196fc84c-5cea-11e7-9452-cb528975bce1.JPG)
> 
> > To fix this you need to make sure the Handler Mappings in Feature Delegation is set to Read/Wite.
> > After that you need to reset delegation.
> 
> If I reset the delegation then it turns back to "Read only". Therefore I set it to "Read/Write" and **I didn't reset all delegation** contrary as you said.
> 
> Also notice ASP.NET has to be installed as detailed in the docs.
> 
> > IIS 7.x with IIS Management Tools and ASP.NET
> 
> Realted with #93

Hi bro 
Thank you so much for fix problem me
