### ISSUE TITLE
IIS Express 64-bit won't start

### ISSUE THREAD

**Issue by modulexcite** [tjanczuk/iisnode#523]
I apologize if someone has already reported this issue in the past and if there is an existing solution for this. 
I'm unable to start the IIS Express 64-bit edition either from command line or Visual Studio and from the looks of the error reported by IIS Express, it seems like it was trying to load the iisnode 32 bit module instead of the 64-bit. However, I can run the IIS Express 32-bit version without any issues as it seems to load the correct version there.

Thank you and keep up the great work, you rock @tjanczuk! 
### OS Version:

Windows 7 64-bit Professional Edition
### IIS Express Version:

10
### IIS Node Versions Installed:

IISNode v0.2.21 Full 64-bit
IISNode v0.2.21 Express 32-bit
### Error Message:

C:\Program Files\IIS Express>iisexpress.exe /trace:error
Starting IIS Express ...
Initializing the W3 Server Started CTC = 1289769
W3 Server initializing WinSock.  CTC = 1289785
W3 Server WinSock initialized.  CTC = 1289785
W3 Server ThreadPool initialized (ipm has signalled).  CTC = 1289785
Failed processing with hr = 800700c1
Error loading global modules.  hr = 800700c1
Terminating W3_SERVER object
Start listenerChannel http:0
Initializing the W3 Server Started CTC = 1290986
W3 Server initializing WinSock.  CTC = 1290986
W3 Server WinSock initialized.  CTC = 1290986
W3 Server ThreadPool initialized (ipm has signalled).  CTC = 1290986
Failed processing with hr = 800700c1
Error loading global modules.  hr = 800700c1
Terminating W3_SERVER object
InitComplete event signalled
Process Model Shutdown called
Unable to start iisexpress.
### Error Message from Event Logs:

The Module DLL 'C:\Program Files (x86)\iisnode-express\iisnode.dll' could not be loaded due to a configuration problem. The current configuration only supports loading images built for a AMD64 processor architecture. The data field contains the error number. To learn more about this issue, including how to troubleshooting this kind of processor architecture mismatch error, see http://go.microsoft.com/fwlink/?LinkId=29349.

**Comment by rthadr** [comment]
Did you look in your %USERPROFILE%\Documents\IISExpress\config\applicationhost.config?  I'd try changing it there to point to the x64 version,  I doubt you can have it both ways at once.

**Comment by modulexcite** [comment]
I no longer use this with IIS Express as a result of this, I will keep this in mind the next time I use it.
Thanks @rthadr

**Comment by devotis** [comment]
@modulexcite I think you should close this issue.
