### ISSUE TITLE
iisnode starts up node process fine but does not serve up any pages

### ISSUE THREAD

**Issue by azcn2503** [tjanczuk/iisnode#528]
I have the following system:
- Windows Server 2012 R2
- IIS 8
- Node v4.5.0 (x86)
- iisnode iisnode v0.2.21 (x64)

I have a Node application that started life as a Meteor application. The Meteor application has been converted to a native Node application using demeteorizer. I know that this process has worked since I am able to run the application using `node main.js` and, with the correct environment variables set, it works. When my PORT environment variable is set to 8080, I can then browse to http://localhost:8080 and I get exactly the same functionality as if I were running the application through Meteor.

I have installed iisnode and set up a site pointing to the demeteorized application. The entry point for the application is a file called main.js.

My web.config looks like this (excluding any rewrite rules for now, since they are not touched right now):

```
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
    <system.webServer>
        <iisnode nodeProcessCommandLine="C:\Program Files (x86)\nodejs\node.exe" />
        <handlers>
            <add name="iisnode" path="main.js" verb="*" modules="iisnode" />
        </handlers>
        <defaultDocument>
            <files>
                <add value="main.js" />
            </files>
        </defaultDocument>
    </system.webServer>
</configuration>
```

The site binding is set to port 80.

When I browse to http://localhost, an error message is displayed in the browser after some seconds:

> iisnode encountered an error when processing the request.

```
HRESULT: 0x2
HTTP status: 500
HTTP subStatus: 1001
HTTP reason: Internal Server Error
```

I can see that a node.exe process starts under the same username as my IIS site name (hubdeploy) after browsing to the site. And now that it is running, I can then browse to http://localhost:8080 and use the application as if I started it using `node main.js`, but obviously I don't get any of the nice features in IIS like rewrite rules and Windows authentication. 

When I look at the log files, I don't see any error messages. I see some stdout messages corresponding to some console.log messages in the application. And in stderr I see a warning about using a pure JS version of bcrypt which is slower than a native implementation (not really an error, the application is working fine outside of IIS).

Any suggestions to get iisnode serving the site? This is the final stage of a deployment project and without IIS being able to serve the pages it's going to be difficult to deliver this to our customers.

**Comment by devotis** [comment]
Your main.js app shouldn't listen to 8080, but to process.env.PORT because that's what IISnode proxies the traffic to it receives on port 80.

Have you been able to fix this in the meantime? Please close the issue if so and share the solution with us if you like.

**Comment by jods4** [comment]
I have the exact same situation.

I have set up an IIS website listening on xyz.server.local:80, installed iisnode (0.2.21), redirected traffic to my `index.js` Express app.

When receiving a request, IIS does start the nodejs process. But then the request hangs for what seems a far too long time and then returns the same answer as the OP.

At this point the nodejs app _is_ running and if I connect directly to server.local:8080 I get its answer perfectly fine. 

So it looks like iisnode has a hard time piping request to/from the nodejs process...

And yes, it seems the port is always 8080, which surprised me because I'm doing `app.listen(process.env.PORT)`.
Is it supposed to be random?
Given the comments above I'm getting a suspicion: could it be that I have a `PORT` env variable already set to 8080? Would that override iisnode somehow and break communication?

I have spent a lot of time trying to get this to work without success, it's terribly frustrating.

**Comment by jods4** [comment]
I had indeed a system PORT=8080 env variable.

Removing it and restarting IIS changed nothing. Strangely it seems the nodejs app still starts on 8080, not sure if this is expected (is it the default port when it's available?)

I gave full permissions to _Everyone_ on the entire folder, doesn't help.

My `console.log` end up nowhere (not in the `*.logs` folder, not on the webpage response), although I'm sure that at one point, _they did_. Can't seem to make it work anymore, though :(

ETW is full of these:
```
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
	<System>
		<Provider Guid="{1040dfc4-61db-484a-9530-584b2735f7f7}" />
		<EventID>0</EventID>
		<Version>0</Version>
		<Level>4</Level>
		<Task>0</Task>
		<Opcode>0</Opcode>
		<Keywords>0x0</Keywords>
		<TimeCreated SystemTime="2017-05-11T11:39:18.235872900Z" />
		<Correlation ActivityID="{00000000-0000-0000-0000-000000000000}" />
		<Execution ProcessID="5472" ThreadID="988" ProcessorID="0" KernelTime="0" UserTime="0" />
		<Channel />
		<Computer />
	</System>
		<Data>{12696D38-0C79-4306-BC89-E3B07D4228BA}: iisnode scheduled a retry of a named pipe connection to the node.exe process </Data>
</Event>
```
Obviously iisnode can't communicate with my nodejs process, although the latter runs fine.

Help?

**Comment by devotis** [comment]
No, 8080 is not to be expected to have your Node.js function properly behind iisnode. The port should be something completely different. I suppose iisnode sets the port environment variable. And your program should not overwrite that to 8080. Somewhere you're setting PORT to 8080. That is the first thing you should fix.

In my case for example if I `console.log(process.env.PORT)`

this is what I get: `\\.\pipe\9967ef2f-36c1-4759-9ea5-ea2191dc44a0`

**Comment by jods4** [comment]
It seems that restarting IIS after deleting the system environment variable was not enough!?.

After restarting the server completely, this is now working.

I'm surprised that having a system env. variable named `PORT` takes precedence over iisnode.

**Comment by azcn2503** [comment]
Removing the PORT environment variable, and using the dynamically allocated one worked. Thanks! And sorry for the delay in getting back!

**Comment by muhannadsnan** [comment]
> process.env.PORT

I wasted days and days deploying node apps on azure but nothing worked for me. I finally tried to listen to this port "process.env.PORT" instead of 3000 or other ports

THANKS YOU! ! !
