### ISSUE TITLE
IIS, Angular, and WebAPI C#.

### ISSUE THREAD

**Issue by brunopbarrote** [tjanczuk/iisnode#545]
I'm having a lot of troubles to make that combination work.

Im using node to serve my angular application, but i trying to create a /api virtual directory on IIS, that will point to a WebAPI C#, but i can't make it work. It always fire nodejs routes and not the IIS directory configured.

Is this a issue? Or am i doing something wrong?

**Comment by brunopbarrote** [comment]
Some help on it?

**Comment by devotis** [comment]
How does your web.config file look like?

**Comment by brunopbarrote** [comment]
Here iis my web.config: [here](https://gist.github.com/brunopbarrote/d53794a553c8027f488d25ef2ed1aeff)
And here is my iis folder looks like: [here](http://i.imgur.com/cUb3bz7.png)

Am i doing something wrong? How can i make /api/ request redirect to api application instead of redirect to server.js?

**Comment by brunopbarrote** [comment]
Any idea? :(

**Comment by devotis** [comment]
What do you see in your iis log file?

Your DynamicContent rule basically says rewrite all requests to server.js. That includes requests to /api right?

I don't know a thing about WebAPI C#, but I guess you need a handler for that that you need to configure in the handlers section in web.config.

Right know I'm guessing that you didn't do anything wrong or that there is an issue as you ask in your first comment. It's just that you didn't configure anything to make sure /api is handled by WebAPI C#.

**Comment by brunopbarrote** [comment]
To make it work, i've made a change to only redirect to server.js
is it doesn't accept /api pattern.


`<?xml version="1.0" encoding="UTF-8"?>
<configuration>
    <system.webServer>
		<handlers>
			<add name="iisnode" path="server.js" verb="*" modules="iisnode" />
		</handlers>
		  <rewrite>  
           <rules>  
                <rule name="LogFile" patternSyntax="ECMAScript" stopProcessing="true">  
                     <match url="iisnode" />  
                </rule>  
				
                <rule name="NodeInspector" patternSyntax="ECMAScript" stopProcessing="true">                      
                    <match url="^server.js\/debug[\/]?" />  
                </rule>
				
				
				<rule name="Main Rule" stopProcessing="true">
					<match url=".*" />
					<conditions logicalGrouping="MatchAll">
					
						
						<add input="{REQUEST_FILENAME}" matchType="IsFile" negate="true" />                                 
						<add input="{REQUEST_FILENAME}" matchType="IsDirectory" negate="true" />
						<add input="{REQUEST_URI}" matchType="Pattern" pattern="api/(.*)" negate="true" />
					</conditions>
					<action type="Rewrite" url="server.js" />
				</rule>
           </rules>  
      </rewrite> 
	  
	   <iisnode node_env="%node_env%" 
				nodeProcessCountPerApplication="1" 
				maxConcurrentRequestsPerProcess="1024" 
				maxNamedPipeConnectionRetry="100" 
				namedPipeConnectionRetryDelay="250" 
				maxNamedPipeConnectionPoolSize="512" 
				maxNamedPipePooledConnectionAge="30000" 
				asyncCompletionThreadCount="0" 
				initialRequestBufferSize="4096" 
				maxRequestBufferSize="65536" 
				watchedFiles="*.js;iisnode.yml" 
				uncFileChangesPollingInterval="5000" 
				gracefulShutdownTimeout="60000" 
				loggingEnabled="true" 
				logDirectory="iisnode" 
				debuggingEnabled="true" 
				debugHeaderEnabled="false" 
				debuggerPortRange="5058-6058" 
				debuggerPathSegment="debug" 
				maxLogFileSizeInKB="128" 
				maxTotalLogFileSizeInKB="1024" 
				maxLogFiles="20" 
				devErrorsEnabled="true" 
				flushResponse="false" 
				enableXFF="false" 
				promoteServerVars="" 
				configOverrides="iisnode.yml" />
				
        <defaultDocument>
            <files>
                <add value="server.js" />
            </files>
        </defaultDocument>
		
    </system.webServer>
</configuration>
`

**Comment by devotis** [comment]
@brunopbarrote please close this issue. Let's keep this place clean.
