### ISSUE TITLE
iisnode thrown the error with sqlpad application

### ISSUE THREAD

**Issue by MongkonEiadon** [tjanczuk/iisnode#553]
I try to deploy [https://github.com/rickbergfalk/sqlpad](sqlpad) application to iisnode, then I saw the error seem like this 

> iisnode encountered an error when processing the request.

HRESULT: 0x2
HTTP status: 500
HTTP subStatus: 1002
HTTP reason: Internal Server Error
You are receiving this HTTP 200 response because system.webServer/iisnode/@devErrorsEnabled configuration setting is 'true'.

In addition to the log of stdout and stderr of the node.exe process, consider using debugging and ETW traces to further diagnose the problem.

The last 64k of the output generated by the node.exe process to stderr is shown below:

Application has thrown an uncaught exception and is terminated:
Error: EPERM: operation not permitted, mkdir 'C:\WINDOWS\system32\config\systemprofile\sqlpad'
    at Object.fs.mkdirSync (fs.js:854:18)
    at sync (C:\nodejsiis\node_modules\mkdirp\index.js:71:13)
    at sync (C:\nodejsiis\node_modules\mkdirp\index.js:77:24)
    at Function.sync (C:\nodejsiis\node_modules\mkdirp\index.js:77:24)
    at Object.<anonymous> (C:\nodejsiis\lib\db.js:9:8)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)

for my web.config file seem like this
`<configuration>
	<appSettings>       

	</appSettings>

	<system.webServer>

		

		<handlers>
			<add name="iisnode" path="server.js" verb="*" modules="iisnode" />
		</handlers>
		
		<rewrite>
			<rules>
				<rule name="cdw">
					<match url="/*" />
					<action type="Rewrite" url="server.js" logRewrittenUrl="true" />
				</rule>
			</rules>
		</rewrite>

	    <iisnode
		    node_env="%node_env%"
      nodeProcessCountPerApplication="1"
      maxConcurrentRequestsPerProcess="1024"
      maxNamedPipeConnectionRetry="100"
      namedPipeConnectionRetryDelay="250"      
      maxNamedPipeConnectionPoolSize="512"
      maxNamedPipePooledConnectionAge="30000"
      asyncCompletionThreadCount="0"
      initialRequestBufferSize="4096"
      maxRequestBufferSize="65536"
      watchedFiles="*.js;iisnode.yml"
      uncFileChangesPollingInterval="5000"      
      gracefulShutdownTimeout="60000"
      loggingEnabled="true"
      logDirectory="iisnode"
      debuggingEnabled="true"
      debugHeaderEnabled="true"
      debuggerPortRange="5058-6058"
      debuggerPathSegment="debug"
      maxLogFileSizeInKB="128"
      maxTotalLogFileSizeInKB="1024"
      maxLogFiles="20"
      devErrorsEnabled="true"
      flushResponse="false"      
      enableXFF="false"
      promoteServerVars=""
      configOverrides="iisnode.yml"
      nodeProcessCommandLine="C:\Program Files (x86)\nodejs\node.exe"/>

	</system.webServer>
</configuration>
`

**Comment by pbaio** [comment]
Your issue doesn't seem to be IISNode, its that the Identity running your IIS App Pool doesn't have permissions to create a directory where your app is trying to.

>Application has thrown an uncaught exception and is terminated:
Error: EPERM: operation not permitted, mkdir 'C:\WINDOWS\system32\config\systemprofile\sqlpad'
at Object.fs.mkdirSync (fs.js:854:18)
at sync (C:\nodejsiis\node_modules\mkdirp\index.js:71:13)
at sync (C:\nodejsiis\node_modules\mkdirp\index.js:77:24)
at Function.sync (C:\nodejsiis\node_modules\mkdirp\index.js:77:24)
at Object. (C:\nodejsiis\lib\db.js:9:8)
at Module._compile (module.js:571:32)
at Object.Module._extensions..js (module.js:580:10)
at Module.load (module.js:488:32)
at tryModuleLoad (module.js:447:12)
at Function.Module._load (module.js:439:3)

**Comment by MongkonEiadon** [comment]
thank you. @pbaio  for your answer but I already grant for everyone permission to read/write. then I found another 'cause my node runtime version is x86 and my iisnode is x64, then I reinstall node.js to x64 and everything work fine so I'll close this issue

thanks
