### ISSUE TITLE
Heap corruption causing crash

### ISSUE THREAD

**Issue by zeiphon** [tjanczuk/iisnode#559]
I'm using iisnode in an Azure web app to host my node application and have noticed that recently it has been continuously restarting (within a matter of seconds or minutes in some cases, or sometimes much longer).
I've checked all of my application logs, iisnode logs (after enabling) and event viewer - but all have yielded nothing. 
I haven't been able to reproduce the problem locally - but I have been able to reproduce it (sporadically) between two different web app deployments.

Utilising CrashDiag on the server, I was able to find that the process is in fact crashing (and not simply being recycled, but w3wp was exiting also) and to make a process dump of w3wp at the time of the crash.
One of these dumps can be found here: 
https://www.dropbox.com/s/y4w9xev2k3ghle0/w3wp_21908_RD000D3AE000CB__.dmp?dl=1

However I lack the expertise to properly diagnose the crash from this dump - if someone would be willing to have a look at it?

A basic crash analysis shows:
```
In w3wp_21908_RD000D3AE000CB.dmp the assembly instruction at ntdll!RtlReportCriticalFailure+33 in D:\Windows\System32\ntdll.dll from Microsoft Corporation has caused a breakpoint exception (0x80000003) on thread 4
```

`A breakpoint exception thrown by a heap memory manager function indicates heap corruption.`

With the stack being the following:
```
ntdll!RtlReportCriticalFailure+34     0000374     7c2e1e8     0e7f3e0     7c1ad11    
ntdll!RtlpReportHeapFailure+21     0000002     2c896c4     07b0000     0fcd760    
ntdll!RtlpLogHeapFailure+a2     0000008     07b0000     0fcd760     0000000    
ntdll!RtlFreeHeap+5c     07b0000     0000000     0fcd768     0e7f464    
iisnode!RegisterModule+183a1     0fcd768     0000006     3901bda     0fcd768    
iisnode!RegisterModule+ce0     0fcd768     0e7f4cc     0e7f4cc     0fcd768    
iisnode!RegisterModule+11787     0000000     0000000     0fcd788     0e7f4cc    
iisnode!RegisterModule+102bd     0000000     0000007     0fcd788     0e7f4cc    
iisnode!RegisterModule+1445d     0fcd788     0000080     0000000     3f81f08    
iiscore!NOTIFICATION_CONTEXT::RequestDoWork+68     47b4700     0e7f53c     3f81f08     0000001    
iiscore!NOTIFICATION_CONTEXT::CallModulesInternal+3bf     0000001     0000007     0000000     0000002    
iiscore!NOTIFICATION_CONTEXT::CallModules+28     0000001     0000007     0000000     0000002    
iiscore!NOTIFICATION_MAIN::DoStateRequestExecuteHandler+3f     0000001     0000007     0000000     0000002    
iiscore!NOTIFICATION_MAIN::DoWork+11a     0000007     0000000     0000002     0000001    
iiscore!W3_CONTEXT_BASE::ContinueNotificationLoop+1d     0000007     0000002     07b1020     07b05c8    
iiscore!W3_MAIN_CONTEXT::OnIoCompletion+76     0000002     07b1038     0000007     0000000    
w3dt!UL_NATIVE_REQUEST::DoWork+9e     0000002     0000007     0000000     07b100c    
w3dt!UL_SEND_CONTEXT::DoWork+1b     0000007     0000000     07b100c     0c32430    
w3dt!WP_CONTEXT::OnCompletion+22     0000000     0000007     07b100c     0c32438    
w3tp!THREAD_POOL_DATA::ThreadPoolThread+a6     4310000     0000000     0c91710     fffffff    
w3tp!THREAD_POOL_DATA::ThreadPoolThread+28     0c32430     0000000     0000000     0c91710    
w3tp!THREAD_MANAGER::ThreadManagerThread+52     0c91710     0e7f9b4     7b99e89     0c91710    
kernel32!BaseThreadInitThunk+e     0c91710     2c89c90     0000000     0000000    
ntdll!__RtlUserThreadStart+72     4311d49     0c91710     fffffff     7c11dd2    
ntdll!_RtlUserThreadStart+1b     4311d49     0c91710     0000000     0000000    
```

I *seem* to be able to sporadically trigger a crash (sometimes it can take quite a while, sometimes it's very quick) by making a certain request to my application which in turn creates a new request to a PhantomJs instance, which then makes a call **back** to the application and returns the rendered output.
The block in question, if it helps, is akin to the following:
```
var request = require('request')
...

app.use(function (req, res, next) {
    // if (condition) ...
    var phantomJsUrl = 'http://my-phantomjs-server/' + params;
    request(phantomJsUrl).pipe(res);
}
```

(This may or may not be related to the issue at hand. The application has also been logging to disk, so if say the error were related to disk I/O, this request could simply be more likely to trigger the error due to a larger amount of log output)

**Comment by rramachand21** [comment]
Could you please try https://github.com/Azure/iisnode/releases/tag/v0.2.24 - I have fixed the w3wp crash issues in this release.

**Comment by zeiphon** [comment]
Hi,

One thing I had noticed is that azure is using iisnode 0.2.23, but haven't been able to see that release anywhere.

Is there any way to actually specify the version of iisnode on Azure?

**Comment by rramachand21** [comment]
v0.2.24 includes fixes from 0.2.23 - I will be releasing v0.2.24 on azure soon as well.

**Comment by zeiphon** [comment]
That's great and I will certainly try it out, but is it possible to tie a Web App to a particular IISNode version for stability?

**Comment by rramachand21** [comment]
Unfortunately no. 0.2.23 already has the w3wp crash issue fixed. v0.2.24 has minor improvements for node process sticky sessions.

**Comment by zeiphon** [comment]
I'm a little confused - when was the w3wp crash fix implemented?
I had a look at Azure's iisnode version about 12 hours ago and it was 0.2.23, and the fix https://github.com/Azure/iisnode/commit/8f9d43a61dd48fe0322eedf020aae457bfba3ea4 seems to have been committed 5 hours ago?

Did you go back and implement the fix in 0.2.23 as well (or am I missing something)?

**Comment by rramachand21** [comment]
I fixed the w3wp crash in 0.2.23 which was released on azure first (released gradually across different regions). I released v0.2.24 here with that and additional fixes. v0.2.24 will go out soon on azure.

**Comment by rramachand21** [comment]
v0.2.23 was first released on a few regions of azure about a month ago.

**Comment by rramachand21** [comment]
Wait a minute, you are seeing these crashes on 0.2.23 ?

**Comment by rramachand21** [comment]
Taking a look at the dump ...

**Comment by zeiphon** [comment]
Yes that's correct, I'm seeing the crashes on 0.2.23

**Comment by rramachand21** [comment]
Would it possible for you to share your app that repro's this?

**Comment by zeiphon** [comment]
Privately perhaps? It's not a very small application (and closed source) - how would you like to do this?

**Comment by rramachand21** [comment]
PLease send me your azure webapp name and I can take a look - send it to ranjithr at microsoft dot com

**Comment by rramachand21** [comment]
https://github.com/Azure/iisnode/releases/tag/v0.2.25 has the fix for this w3wp crash.

**Comment by zeiphon** [comment]
For the record, Ranjith very kindly got in touch and examined the crash in order to figure out this issue, which turned out the be related to response flushing, specifically `IHttpResponse->Flush()`.

I'll do some further testing today and tomorrow to double check that there's no more crashing.

**Comment by rramachand21** [comment]
Thanks Jonathon 👍

**Comment by zeiphon** [comment]
Initial testing is showing that stability seems to have returned, haven't been able to cause the crash so far!

Please keep us updated on when this fix will go out on Azure (to which regions etc) if you don't mind?

**Comment by rramachand21** [comment]
Sure, I found out another case where the refcount would cause an issue - If you enable debugging, w3wp might crash. I am going to release another version with this fix.

I will keep you update on the release on azure.

**Comment by rramachand21** [comment]
https://github.com/Azure/iisnode/releases/tag/v0.2.26 has the fix for the issue mentioned in the above comment.

**Comment by rramachand21** [comment]
This is the version that will be released on Azure.

**Comment by zeiphon** [comment]
Hi Ranjith, any ETA on the release of your fix to Azure South East
Australia?
My production is suffering quite a lot with continuous restarts, and I'm
wondering if I should spend some time making my application work in a VM
since web apps require the use of IISNode.

**Comment by rramachand21** [comment]
could you please mail me your sitename (prod)?

**Comment by zeiphon** [comment]
Sure, it's named "augamesearch"

**Comment by rramachand21** [comment]
btw, is it possible for your to disable flushResponse in the iisnode config ? You dont need this unless you are streaming data

**Comment by zeiphon** [comment]
ah my site does use streaming quite a bit

**Comment by zeiphon** [comment]
Hmm, it will work without streaming but not very well - I can try disabling
it

**Comment by rramachand21** [comment]
The quickest way to fix would be to disable flushResponse (this would be the temporary workaround). 
And then once the fix is available, (which will take atleast 2 weeks to be deployed), you can enable flushResponse or any other setting..

**Comment by zeiphon** [comment]
(closing as I noticed that this issue was still open)
