### ISSUE TITLE
get IIS authenticated user name in a Nodejs app

### ISSUE THREAD

**Issue by brucelane** [tjanczuk/iisnode#575]
Hi,
I'm sorry if it's not the right place to ask, but I can't find a way to pass the authenticated user name (or login) to a nodejs app. 
I use iisnode mainly for this reason, so in my local Intranet, I can use Single Sign On (Windows Authentication on a local Active Directory domain) and get the user properties in ASP/ASP.net, my REST API is in nodejs...
Any hint greatly appreciated!

**Comment by psalessi** [comment]
Hey not sure if you solved this yet, but I had a similar question and https://github.com/tjanczuk/iisnode/issues/87 details how you can promote and read the AUTH_USER server variable. 

If you set up Windows Authentication with IIS, you should be able to make this work for your needs.

**Comment by brucelane** [comment]
yes, I used Windows Authentication, I can get the user name in a asp.net website written in C#.
It seems it's not possible, I think I have to write my server in C# then?

**Comment by brucelane** [comment]
it works fine now, I'm closing this, thank you very much!
