### ISSUE TITLE
restart node.exe if dependent files are updated

### ISSUE THREAD

**Issue by kirillg** [tjanczuk/iisnode#58]
Currently, IISNode restarts node.exe if the associated .js file is updated. Pretty common my app consists of the main app.js and some module foo.js that app.js depends on (require('foo.js'). 

As I debug issues in foo.js, I often update it without updating app.js. I have to remember to restart IISNode. Could we either
a) provide an explicit descriptor of dependencies
  or, better yet,
b) track the .js files we load at runtime and re-load node.exe if any of the loaded .js filed got updated.
?

**Comment by hmny** [comment]
For some reason this doesn't work for me too. Even when I want to make a change to a single `server.js` file, sometimes it updates automatically but most of the time I need to restart it manually.

**Comment by scottchantry** [comment]
My starting point for my app is in a 'bin' folder.  How would I specify files in a higher lever to the entry point? Would I use something like: '../*.js'

**Comment by shushiej** [comment]
has there been a fix to this, as I am also facing the same problem. 
I am using express to start my server:

`
const express = require('express');
const app = express();
app.use('/api/roadmaps', roadmapsRouter);
app.get('/', function root(req, res) {
  res.sendFile(__dirname + '/index.html');
});

app.listen(process.env.PORT || 3000);
console.log('server started on port', process.env.PORT || 3000);`
And my web.config looks like this
`<configuration>
   <system.webServer>

     

     <handlers>
       <add name="iisnode" path="server.js" verb="*" modules="iisnode" />
     </handlers>
	
     <iisnode watchedFiles="web.config;*.js;index.html" nodeProcessCommandLine="C:\Program Files\nodejs\node.exe" />

     <rewrite>
       <rules>
         <rule name="api">
           <match url="api/*" />
           <action type="Rewrite" url="server.js" />
         </rule>
       </rules>
     </rewrite>

     
     
     <security>
       <requestFiltering>
         <hiddenSegments>
           <add segment="node_modules" />
         </hiddenSegments>
       </requestFiltering>
     </security>    
     
   </system.webServer>
 </configuration>`

This is a React based application and when i make a change to a any of my components under the path 
/src/components/*/*.js there doesnt seem to be a any change in the iisnode application, and I am not able to see any changes to the app. I tried manually restarting the IIS site but that didn't work either.
