### ISSUE TITLE
No images in debug documentation

### ISSUE THREAD

**Issue by szarouski** [tjanczuk/iisnode#582]
Hi, I'm running latest iisnode & when I hit an error I see following:
![image](https://user-images.githubusercontent.com/911388/27351652-14cb3bde-55cc-11e7-9e49-91d9cdb927a7.png)

There is a debugging link which takes to https://tomasz.janczuk.org/2011/11/debug-nodejs-applications-on-windows.html but all images are gone from that article :(. Is it possible for you to re-upload them?

![image](https://user-images.githubusercontent.com/911388/27351721-48386b40-55cc-11e7-9182-5438188840b4.png)

Thank you.

**Comment by MariannaAtPlay** [comment]
Yes, please! I would love that too!

**Comment by szarouski** [comment]
I think author of this project has no bandwidth to maintain it anymore.

**Comment by blowsie** [comment]
Duplicates #537

**Comment by szarouski** [comment]
Thanks @blowsie , closing as a duplicate.
