### ISSUE TITLE
The requested page cannot be accessed because the related configuration data for the page is invalid.

### ISSUE THREAD

**Issue by dimoibiehg** [tjanczuk/iisnode#594]
I have gotten the following error when running all samples:

![image](https://user-images.githubusercontent.com/22638310/30253189-6083afa2-9695-11e7-862a-b9d7ee487b9e.png)

**Comment by BigZolo** [comment]
Open IIS Manager, find Management/Feature Delegation and change _Handler Mapping_ to Read/Write
