### ISSUE TITLE
HTTP error 500.19 internal server error

### ISSUE THREAD

**Issue by Prince269090** [tjanczuk/iisnode#618]
Hi, I am trying to deploy app written using express.js to new root website in iis using iisnode and am getting the following error while accessing [http://localhost/node/helloworld/helloworld.js](HelloWorld.js) in IIS 7.

**HTTP Error 500.19 - Internal Server Error**
The requested page cannot be accessed because the related configuration data for the page is invalid.

**Config Error** | This configuration section cannot be used at this path. This happens when the section is locked at a parent level. Locking is either by default (overrideModeDefault="Deny"), or set explicitly by a location tag with overrideMode="Deny" or the legacy allowOverride="false".

**Note :** 

- I have already installed NodeIIS and URLRewrite. 
- I am able to see the Node module in my IIS.

![image](https://user-images.githubusercontent.com/34852023/35027547-528d1d24-fb77-11e7-8f1d-529f802ef8fb.png)

![image](https://user-images.githubusercontent.com/34852023/34986314-2730c7d8-fadd-11e7-9dc0-1cf1a5ad3aff.png)

**IIS Version**

![image](https://user-images.githubusercontent.com/34852023/34986373-5bf781dc-fadd-11e7-9430-05c6aec762ac.png)

**Comment by sergeos** [comment]
Show web.config

**Comment by Prince269090** [comment]
<configuration>
  <system.webServer>

    

    <handlers>
      <add name="iisnode" path="hello.js" verb="*" modules="iisnode" />
    </handlers>
    
  </system.webServer>
</configuration>

**Comment by Prince269090** [comment]
I have found the solution myself. We just have to enable few features of the IIS as mentioned in [https://stackoverflow.com/questions/9794985/iis-this-configuration-section-cannot-be-used-at-this-path-configuration-lock](url)
