### ISSUE TITLE
child_process.fork() fails with process exit error code 1 but no other information available

### ISSUE THREAD

**Issue by rfreas** [tjanczuk/iisnode#629]
I think this is repo is old and not being actively maintained, but it has more activity/watchers, etc, so wanted to post my issue here, too.

Please see https://github.com/Azure/iisnode/issues/52 or read below.  Thanks!

--

I am encountering a strange issue with iisnode on Azure. Basically, the issue is child_process.fork() seems to not work and doesn't throw errors. I've tried attaching to the uncaughtException event, combing the logs, and so on -- but the only information I get is from the "exit" process event and the error code is 1, which means uncaught exception. No other information is available. For the .js file that I am forking, I can run it manually with the exact same command line in the Kudu command line prompt and it runs fine. But when executed via child_process.fork(), I don't even see the initial console.log() statement execute. I know the child process is being spawned because I can see it in the Kudu process list with the proper command line and with access to all the same environment variables, and so on. I am using the latest version of node.exe which is 8.8.4, though initially it was running on whatever the default version was when I setup the original stub template in Azure (node 4.2.4).

I tried creating a new TestFork.t/js file which just forks the other .js file and I used this command line in the Kudu console: "D:\Program Files (x86)\nodejs\8.8.0\node.exe" .\Services\TestFork.js. It worked in the sense that the child process was running and I could see logging and other output. So I wonder what's going on when running in the context of iisnode. Could there be a permissions issue or something else? The forked js file downloads files using wget to a temp folder (d:\home\site\temp, the app creates it if it doesn't exist during start up), so there's some read/write file i/o but that seems to run fine as I can see the files being created and later deleted via fs.unlinkSync(), etc.

If there's really an uncaughtException as error code 1 suggests, how come I can't seem to catch it in a try/catch around the child_process.fork() call, or by listening to process.on uncaughtException or child.on uncaughtException, etc.?

Does anyone have thoughts as to what might be going on?

Here's my web.config:
```
<system.web>
    <customErrors mode="off" />
</system.web>

<system.webServer>
    <httpErrors existingResponse="PassThrough" />

    <handlers>
        <!-- indicates that the app.js file is a node.js application to be handled by the iisnode module -->
        <add name="iisnode" path="index.js" verb="*" modules="iisnode" />
    </handlers>

    <rewrite>
        <rules>
            <!-- Don't interfere with requests for logs -->
            <rule name="LogFile" patternSyntax="ECMAScript" stopProcessing="true">
                <match url="^[a-zA-Z0-9_\-]+\.js\.logs\/\d+\.txt$" />
            </rule>

            <!-- Don't interfere with requests for node-inspector debugging -->
            <rule name="NodeInspector" patternSyntax="ECMAScript" stopProcessing="true">                    
                <match url="^index.js\/debug[\/]?" />
            </rule>
          
            <!-- First we consider whether the incoming URL matches a physical file in the /public folder -->
            <rule name="StaticContent">
                <action type="Rewrite" url="public{REQUEST_URI}" />
            </rule>

            <!-- All other URLs are mapped to the Node.js application entry point -->
            <rule name="DynamicContent">
                <conditions>
                    <add input="{REQUEST_FILENAME}" matchType="IsFile" negate="True" />
                </conditions>
                <action type="Rewrite" url="index.js" />
            </rule>
        </rules>
    </rewrite>
    
    <iisnode
      loggingEnabled="true"
      devErrorsEnabled="true"
     />

</system.webServer>
```

**Comment by jholster** [comment]
Hi, did you ever found the problem?
