### ISSUE TITLE
IISnode not compatible with Windows Server 2016?

### ISSUE THREAD

**Issue by mmuneer** [tjanczuk/iisnode#638]
Hello,
I am trying to deploy a node app on Windows Server 2016 using IIS node. Here is the error I get when I try to access the site:

iisnode encountered an error when processing the request.

HRESULT: 0x2
HTTP status: 500
HTTP subStatus: 1002
HTTP reason: Internal Server Error
You are receiving this HTTP 200 response because system.webServer/iisnode/@devErrorsEnabled configuration setting is 'true'.

In addition to the log of stdout and stderr of the node.exe process, consider using debugging and ETW traces to further diagnose the problem.

The last 64k of the output generated by the node.exe process to stderr is shown below:

Application has thrown an uncaught exception and is terminated:
SyntaxError: Unexpected token )
    at Module._compile (module.js:437:25)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:362:17)
    at require (module.js:378:17)
    at Object.<anonymous> (C:\Program Files\iisnode\interceptor.js:210:1)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:356:32)

Here is what my server.js looks like:
**Server.js**
```
require('log-timestamp');
const app = require('./app.js');

app.set('port', process.env.PORT || 3001);

app.listen(app.get('port'), () => {
    console.log(`Express server listening on port ${app.get('port')}...`);
});

// Last resort error handling in production. Don't allow error to take down site
if (process.env.NODE_ENV === 'production') {
    process.on('uncaughtException', (err) => {
        console.error(`Server: Exception was not properly handled in code and bubbled up to process: ${err}`);
    });

    process.on('unhandledRejection', (reason, p) => {
        console.error(`Server: Rejection was not properly handled in code and bubbled up to process at: ${p} reason: ${reason}`);
    });
}

```
Here is web.config:

**Web.Config:**
```
<configuration>
  <system.webServer>
    <!-- Visit http://blogs.msdn.com/b/windowsazure/archive/2013/11/14/introduction-to-websockets-on-windows-azure-web-sites.aspx for more information on WebSocket support -->
    <webSocket enabled="false" />
    <handlers>
      <!-- Indicates that the server.js file is a node.js site to be handled by the iisnode module -->
      <add name="iisnode" path="server.js" verb="*" modules="iisnode"/>
    </handlers>
    <rewrite>
      <rules>
        <rule name="LogFile" patternSyntax="ECMAScript" stopProcessing="true">
          <match url="iisnode" />
        </rule>
        <!-- Do not interfere with requests for node-inspector debugging -->
        <rule name="NodeInspector" patternSyntax="ECMAScript" stopProcessing="true">
          <match url="^server.js\/debug[\/]?" />
        </rule>

        <!-- First we consider whether the incoming URL matches a physical file in the /public folder -->
        <rule name="StaticContent">
          <action type="Rewrite" url="public{REQUEST_URI}"/>
        </rule>

        <!-- All other URLs are mapped to the node.js site entry point -->
        <rule name="DynamicContent">
          <conditions>
            <add input="{REQUEST_FILENAME}" matchType="IsFile" negate="True"/>
          </conditions>
          <action type="Rewrite" url="server.js"/>
        </rule>
      </rules>
    </rewrite>

<iisnode
      node_env="production"
      promoteServerVars="AUTH_USER,AUTH_TYPE,LOGON_USER,APP_POOL_ID"
      loggingEnabled="true"
      maxLogFileSizeInKB="1024"
      maxTotalLogFileSizeInKB="8196" />
  </system.webServer>
</configuration>
```

Does anyone know how to resolve this?

**Comment by mmuneer** [comment]
It was due incompatibility with the node version my App was using. Upgraded the node version everything worked!

**Comment by elperez** [comment]
hello @mmuneer , I hope you don't mind me asking. May I know what IIS version you are using? and which steps you followed? thank you.
