### ISSUE TITLE
Windows authentication issue with NodeSSPI, in IIS

### ISSUE THREAD

**Issue by Anirban-Ghatak** [tjanczuk/iisnode#658]
I am trying to get windows authentication set up in a node js application in IIS (Windows) server.
Using node-sspi for windows authentication.
When i started my node server from command prompt windows authentication works well but when i deployed in IIS Server windows auth prompting continuously even after valid credentials .
Got there is an issue in web.config file only . Can anyone suggest please .
![webconfig](https://user-images.githubusercontent.com/43899712/52205661-ca44e500-289d-11e9-9066-0ca328b8deb8.JPG)

**Comment by NareshPalza** [comment]
Hi Anirban, I'm having the same issue. did you find out any resolution? Can you please post.

**Comment by ashonweb** [comment]
any update on this? works fine in local yet when deployed in IIS ,asks continuous credentials even after giving correct. Upon canceling throws unauthorized error.
If there is any work around. Please do post

**Comment by fedorbirjukov** [comment]
Does promoting the variables as described in [this comment](https://github.com/tjanczuk/iisnode/issues/87#issuecomment-3452395) help?

```
<iisnode promoteServerVars="AUTH_USER,AUTH_TYPE" />
```

Also: maybe you should open an issue on [azure/iisnode](https://github.com/azure/iisnode).

**Comment by kirankumarch21** [comment]
Any Update on this. Even I am facing the same issue
