### ISSUE TITLE
provide access to the windows identity of the authenticated user to node.js app

### ISSUE THREAD

**Issue by tjanczuk** [tjanczuk/iisnode#87]
When IIS is configured to require windows authentication, there is currently no way within the node.js application to determine the name of the authenticated user. This is to provide a mechanism to access that username. One possibility is to use X-\* HTTP request headers to convey this information from iisnode to node.exe on a per-request basis. 

This is from http://tomasz.janczuk.org/2011/08/using-url-rewriting-with-nodejs.html?showComment=1321821547800#c8998354757283280788.

**Comment by nathanfrancy** [comment]
@tjanczuk I know this has been here for a while now, but how would I replicate this without IIS or apache? I'm developing locally and just running the express app through command line/webstorm.

**Comment by cutechsupport** [comment]
Hi @tjanczuk,

I follow your above instruction, but still, I cannot retrieve my logged username, please help to resolve.

**My code below:
Config.xlm:**
<configuration>
    <system.webServer> 
       <iisnode 
            promoteServerVars="AUTH_USER,AUTH_TYPE"
            nodeProcessCommandLine="D:\PO\SSO\SSONODEIIS\node.exe" 
       />
        <handlers>
            <add name="iisnode" path="app.js" verb="*" modules="iisnode" />
        </handlers> 

        <rewrite>
            <rules>
                <rule name="sendToNode">
                    <match url="/*" />
                    <action type="Rewrite" url="app.js" />
                </rule>
            </rules>
        </rewrite>  
    </system.webServer>
</configuration>

**app.js:**
'use strict'; 
var http = require('http');  
var getUserGroups = function(user, callback) {
    var ad = new ActiveDirectory(config);
    return ad.getGroupMembershipForUser(`${user}@${domain}`, callback);
};

http.createServer(function(req, res) {
    res.writeHead(200, { 'Content-Type': 'text/plain' });
    var username = req.headers['x-iisnode-auth_user'];
    var authenticationType = req.headers['x-iisnode-auth_type'];  
    res.end('UserName => ' + username + '& AuthType => ' + authenticationType); 
}).listen(process.env.PORT); 

I got empty username and authenticationType, any thing i want to do in the code or iis config?
please help to resolve

Thanks.
